//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.06 at 11:22:44 AM IST 
//


package net.cbtltd.rest.tripvillas.xmlfeed.accommodations;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.cbtltd.rest.tripvillas.xmlfeed.accommodations package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.cbtltd.rest.tripvillas.xmlfeed.accommodations
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accommodations }
     * 
     */
    public Accommodations createAccommodations() {
        return new Accommodations();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation }
     * 
     */
    public Accommodations.Accommodation createAccommodationsAccommodation() {
        return new Accommodations.Accommodation();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Rooms }
     * 
     */
    public Accommodations.Accommodation.Rooms createAccommodationsAccommodationRooms() {
        return new Accommodations.Accommodation.Rooms();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Rooms.Room }
     * 
     */
    public Accommodations.Accommodation.Rooms.Room createAccommodationsAccommodationRoomsRoom() {
        return new Accommodations.Accommodation.Rooms.Room();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Rooms.Room.Amenities }
     * 
     */
    public Accommodations.Accommodation.Rooms.Room.Amenities createAccommodationsAccommodationRoomsRoomAmenities() {
        return new Accommodations.Accommodation.Rooms.Room.Amenities();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Images }
     * 
     */
    public Accommodations.Accommodation.Images createAccommodationsAccommodationImages() {
        return new Accommodations.Accommodation.Images();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Location }
     * 
     */
    public Accommodations.Accommodation.Location createAccommodationsAccommodationLocation() {
        return new Accommodations.Accommodation.Location();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Amenities }
     * 
     */
    public Accommodations.Accommodation.Amenities createAccommodationsAccommodationAmenities() {
        return new Accommodations.Accommodation.Amenities();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Activities }
     * 
     */
    public Accommodations.Accommodation.Activities createAccommodationsAccommodationActivities() {
        return new Accommodations.Accommodation.Activities();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Restrictions }
     * 
     */
    public Accommodations.Accommodation.Restrictions createAccommodationsAccommodationRestrictions() {
        return new Accommodations.Accommodation.Restrictions();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Rooms.Room.Amenities.Amenity }
     * 
     */
    public Accommodations.Accommodation.Rooms.Room.Amenities.Amenity createAccommodationsAccommodationRoomsRoomAmenitiesAmenity() {
        return new Accommodations.Accommodation.Rooms.Room.Amenities.Amenity();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Images.Image }
     * 
     */
    public Accommodations.Accommodation.Images.Image createAccommodationsAccommodationImagesImage() {
        return new Accommodations.Accommodation.Images.Image();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Location.Address }
     * 
     */
    public Accommodations.Accommodation.Location.Address createAccommodationsAccommodationLocationAddress() {
        return new Accommodations.Accommodation.Location.Address();
    }

    /**
     * Create an instance of {@link Accommodations.Accommodation.Location.GeoCode }
     * 
     */
    public Accommodations.Accommodation.Location.GeoCode createAccommodationsAccommodationLocationGeoCode() {
        return new Accommodations.Accommodation.Location.GeoCode();
    }

}
