INSERT INTO attribute (List, ID, Name, Type, Definition, Date) VALUES
('BEP',0, 'Beverage', 'RZ', 'Beverage Preference', NOW()),
('BEP',1, 'Bourbon', 'NO', 'Beverage Preference', NOW()),
('BEP',2, 'Bordeaux', 'NO', 'Beverage Preference', NOW()),
('BEP',3, 'Brandy', 'NO', 'Beverage Preference', NOW()),
('BEP',4, 'Cabernet Sauvignon', 'NO', 'Beverage Preference', NOW()),
('BEP',5, 'Chardonnay', 'NO', 'Beverage Preference', NOW()),
('BEP',6, 'Chianti', 'NO', 'Beverage Preference', NOW()),
('BEP',7, 'Coffee', 'NO', 'Beverage Preference', NOW()),
('BEP',8, 'Hot Tea', 'NO', 'Beverage Preference', NOW()),
('BEP',9, 'Iced Tea', 'NO', 'Beverage Preference', NOW()),
('BEP',10, 'Merlot', 'NO', 'Beverage Preference', NOW()),
('BEP',11, 'Pinot Grigio', 'NO', 'Beverage Preference', NOW()),
('BEP',12, 'Pinot Noir', 'NO', 'Beverage Preference', NOW()),
('BEP',13, 'Red Wine', 'NO', 'Beverage Preference', NOW()),
('BEP',14, 'Red Zinfandel', 'NO', 'Beverage Preference', NOW()),
('BEP',15, 'Rose', 'NO', 'Beverage Preference', NOW()),
('BEP',16, 'Sake', 'NO', 'Beverage Preference', NOW()),
('BEP',17, 'Shiraz', 'NO', 'Beverage Preference', NOW()),
('BEP',18, 'Soda/pop', 'NO', 'Beverage Preference', NOW()),
('BEP',19, 'Vodka', 'NO', 'Beverage Preference', NOW()),
('BEP',20, 'Water', 'NO', 'Beverage Preference', NOW()),
('BEP',21, 'Whiskey', 'NO', 'Beverage Preference', NOW()),
('BEP',22, 'White Wine', 'NO', 'Beverage Preference', NOW()),
('BEP',23, 'White Zinfandel', 'NO', 'Beverage Preference', NOW()),
('BEP',24, 'Gin', 'NO', 'Beverage Preference', NOW()),
('BEP',25, 'Rum', 'NO', 'Beverage Preference', NOW()),
('BEP',26, 'Tequila', 'NO', 'Beverage Preference', NOW()),
('BEP',27, 'Red Wine', 'RZ', 'Beverage Preference', NOW()),
('BEP',28, 'White Wine', 'RZ', 'Beverage Preference', NOW()),
('BEP',29, 'Sparkling Wine', 'RZ', 'Beverage Preference', NOW()),
('BEP',30, 'Beer', 'RZ', 'Beverage Preference', NOW()),
('BEP',31, 'Non Alcholic', 'RZ', 'Beverage Preference', NOW()),
('COM', 0, 'Communication Options', 'RZ', 'Options for communicating', NOW()),
('COM', 1, 'Email', 'RZ', 'Options for communicating', NOW()),
('COM', 2, 'Phone Business Hours', 'RZ', 'Options for communicating', NOW()),
('COM', 3, 'Phone After Hours', 'RZ', 'Options for communicating', NOW()),
('COM', 4, 'Mobile Phone', 'RZ', 'Options for communicating', NOW()),
('COM', 5, 'Fax Phone', 'NO', 'Options for communicating', NOW()),
('COM', 6, 'Skype Phone', 'NO', 'Options for communicating', NOW()),
('COM', 7, 'Facebook', 'NO', 'Options for communicating', NOW()),
('COM', 8, 'Twitter', 'NO', 'Options for communicating', NOW()),
('COM', 9, 'Postal Service', 'NO', 'Options for communicating', NOW()),
('GRP', 0, 'Group Preferences', 'RZ', 'Preferences for grouping', NOW()),
('GRP', 1, 'Individual Person', 'RZ', 'Preferences for grouping', NOW()),
('GRP', 2, 'Single Couple', 'RZ', 'Preferences for grouping', NOW()),
('GRP', 3, 'Family Group', 'RZ', 'Preferences for grouping', NOW()),
('GRP', 4, 'Larger Group', 'RZ', 'Preferences for grouping', NOW()),
('GRP', 5, 'Travel Package', 'RZ', 'Preferences for grouping', NOW()),
('GUP',0, 'Guest Type', 'NO', 'Guest Type', NOW()),
('GUP',1, 'Corporate Employee', 'NO', 'Guest Type', NOW()),
('GUP',2, 'Corporate Transient', 'NO', 'Guest Type', NOW()),
('GUP',3, 'Frequent Guest', 'NO', 'Guest Type', NOW()),
('GUP',4, 'Leisure', 'NO', 'Guest Type', NOW()),
('GUP',5, 'Meeting Attendee', 'NO', 'Guest Type', NOW()),
('GUP',6, 'VIP', 'NO', 'Guest Type', NOW()),
('HAP',0, 'Amenities', 'NO', 'Facility Preferences', NOW()),
('HAP',1, 'Front Desk 24h', 'NO', 'Facility Preferences', NOW()),
('HAP',2, 'Room Service 24h', 'NO', 'Facility Preferences', NOW()),
('HAP',5, 'Air Conditioning', 'NO', 'Facility Preferences', NOW()),
('HAP',7, 'ATM Nearby', 'NO', 'Facility Preferences', NOW()),
('HAP',8, 'Baby Sitting', 'NO', 'Facility Preferences', NOW()),
('HAP',14, 'Library', 'NO', 'Facility Preferences', NOW()),
('HAP',17, 'Check Cashing', 'NO', 'Facility Preferences', NOW()),
('HAP',19, 'Cocktail Lounge', 'NO', 'Facility Preferences', NOW()),
('HAP',25, 'Courtyard', 'NO', 'Facility Preferences', NOW()),
('HAP',26, 'Currency Exchange', 'NO', 'Facility Preferences', NOW()),
('HAP',33, 'Elevators', 'NO', 'Facility Preferences', NOW()),
('HAP',35, 'Exercise Gym', 'NO', 'Facility Preferences', NOW()),
('HAP',41, 'Airport Shuttle', 'NO', 'Facility Preferences', NOW()),
('HAP',42, 'Parking Free', 'NO', 'Facility Preferences', NOW()),
('HAP',43, 'Transport Free', 'NO', 'Facility Preferences', NOW()),
('HAP',44, 'Games Room', 'NO', 'Facility Preferences', NOW()),
('HAP',49, 'Heated Pool', 'NO', 'Facility Preferences', NOW()),
('HAP',50, 'Serviced Daily', 'NO', 'Facility Preferences', NOW()),
('HAP',51, 'Serviced Weekly', 'NO', 'Facility Preferences', NOW()),
('HAP',52, 'Ice Machine', 'NO', 'Facility Preferences', NOW()),
('HAP',53, 'Parking Indoors', 'NO', 'Facility Preferences', NOW()),
('HAP',54, 'Pool Indoors', 'NO', 'Facility Preferences', NOW()),
('HAP',55, 'Jacuzzi', 'NO', 'Facility Preferences', NOW()),
('HAP',57, 'Kennels', 'NO', 'Facility Preferences', NOW()),
('HAP',58, 'Laundry Service', 'NO', 'Facility Preferences', NOW()),
('HAP',61, 'Massage Services', 'NO', 'Facility Preferences', NOW()),
('HAP',63, 'Parking Offsite', 'NO', 'Facility Preferences', NOW()),
('HAP',64, 'Parking Onsite', 'NO', 'Facility Preferences', NOW()),
('HAP',65, 'Parking Outside', 'NO', 'Facility Preferences', NOW()),
('HAP',66, 'Pool Outside', 'NO', 'Facility Preferences', NOW()),
('HAP',71, 'Pool', 'NO', 'Facility Preferences', NOW()),
('HAP',75, 'Parking Rvs', 'NO', 'Facility Preferences', NOW()),
('HAP',77, 'Room Service', 'NO', 'Facility Preferences', NOW()),
('HAP',78, 'Safe Deposit Box', 'NO', 'Facility Preferences', NOW()),
('HAP',79, 'Sauna', 'NO', 'Facility Preferences', NOW()),
('HAP',86, 'Steam Bath', 'NO', 'Facility Preferences', NOW()),
('HAP',87, 'Storage Space', 'NO', 'Facility Preferences', NOW()),
('HAP',96, 'Dry Cleaning', 'NO', 'Facility Preferences', NOW()),
('HAP',100, 'Wakeup Service', 'NO', 'Facility Preferences', NOW()),
('HAP',103, 'Multilingual Staff', 'NO', 'Facility Preferences', NOW()),
('HAP',104, 'Wedding Services', 'NO', 'Facility Preferences', NOW()),
('HAP',105, 'Banquet Facilities', 'NO', 'Facility Preferences', NOW()),
('HAP',106, 'Bell Staff/Porter', 'NO', 'Facility Preferences', NOW()),
('HAP',108, 'Laundry Self Service', 'NO', 'Facility Preferences', NOW()),
('HAP',109, 'Direct Dial Phone', 'NO', 'Facility Preferences', NOW()),
('HAP',112, 'Stables', 'NO', 'Facility Preferences', NOW()),
('HAP',113, '120 Ac', 'NO', 'Facility Preferences', NOW()),
('HAP',115, '220 Ac', 'NO', 'Facility Preferences', NOW()),
('HAP',118, 'Barbeque Grill', 'NO', 'Facility Preferences', NOW()),
('HAP',123, 'Video Games', 'NO', 'Facility Preferences', NOW()),
('HAP',136, 'Butler Service', 'NO', 'Facility Preferences', NOW()),
('HAP',137, 'Coffee/Tea In Room', 'NO', 'Facility Preferences', NOW()),
('HAP',138, 'Breakfast Free', 'NO', 'Facility Preferences', NOW()),
('HAP',143, 'Restaurant Delivery', 'NO', 'Facility Preferences', NOW()),
('HAP',147, 'Evening Reception', 'NO', 'Facility Preferences', NOW()),
('HAP',148, 'Front Desk', 'NO', 'Facility Preferences', NOW()),
('HAP',149, 'Grocery Shopping Service', 'NO', 'Facility Preferences', NOW()),
('HAP',150, 'Halal Food', 'NO', 'Facility Preferences', NOW()),
('HAP',151, 'Kosher Food', 'NO', 'Facility Preferences', NOW()),
('HAP',152, 'Limousine Service', 'NO', 'Facility Preferences', NOW()),
('HAP',165, 'Lounge/Bar', 'NO', 'Facility Preferences', NOW()),
('HAP',171, 'Parking Fee', 'NO', 'Facility Preferences', NOW()),
('HAP',172, 'Transport Fee', 'NO', 'Facility Preferences', NOW()),
('HAP',186, 'Parking On Street', 'NO', 'Facility Preferences', NOW()),
('HAP',193, 'Childrens Play Area', 'NO', 'Facility Preferences', NOW()),
('HAP',194, 'Childrens Nursery', 'NO', 'Facility Preferences', NOW()),
('HAP',196, 'Early Check-In', 'NO', 'Facility Preferences', NOW()),
('HAP',198, 'Non-smoking Rooms', 'NO', 'Facility Preferences', NOW()),
('HAP',201, 'Baggage Hold', 'NO', 'Facility Preferences', NOW()),
('HAP',204, 'Late Check-Out', 'NO', 'Facility Preferences', NOW()),
('HAP',208, 'Turndown Service', 'NO', 'Facility Preferences', NOW()),
('HAP',218, 'Children Welcome', 'NO', 'Facility Preferences', NOW()),
('HAP',219, 'Courtesy Car', 'NO', 'Facility Preferences', NOW()),
('HAP',221, 'WiFi Hotspot', 'NO', 'Facility Preferences', NOW()),
('HAP',223, 'Internet Free', 'NO', 'Facility Preferences', NOW()),
('HAP',226, 'Catering Services', 'NO', 'Facility Preferences', NOW()),
('HAP',240, 'Hair Dryer', 'NO', 'Facility Preferences', NOW()),
('HAP',241, 'Ironing Board', 'NO', 'Facility Preferences', NOW()),
('HAP',242, 'Heated Rooms', 'NO', 'Facility Preferences', NOW()),
('HAP',243, 'Toilet', 'NO', 'Facility Preferences', NOW()),
('HAP',253, 'Private Pool', 'NO', 'Facility Preferences', NOW()),
('HAP',259, 'Internet Fee', 'NO', 'Facility Preferences', NOW()),
('HAP',262, 'Kitchenette', 'NO', 'Facility Preferences', NOW()),
('HAP',263, 'Private Bath/Shower', 'NO', 'Facility Preferences', NOW()),
('HAP',277, 'Pay Phones', 'NO', 'Facility Preferences', NOW()),
('LOP',0, 'Location Preference', 'NO', 'Location Preferences', NOW()),
('LOP',1, 'Airport', 'NO', 'Location Preferences', NOW()),
('LOP',3, 'City', 'NO', 'Location Preferences', NOW()),
('LOP',6, 'Expressway', 'NO', 'Location Preferences', NOW()),
('LOP',7, 'Lake', 'NO', 'Location Preferences', NOW()),
('LOP',8, 'Mountain', 'NO', 'Location Preferences', NOW()),
('LOP',10, 'Resort', 'NO', 'Location Preferences', NOW()),
('LOP',11, 'Rural', 'NO', 'Location Preferences', NOW()),
('LOP',13, 'Suburban', 'NO', 'Location Preferences', NOW()),
('LOP',15, 'Beachfront', 'NO', 'Location Preferences', NOW()),
('LOP',16, 'Oceanfront', 'NO', 'Location Preferences', NOW()),
('LOP',18, 'Business District', 'NO', 'Location Preferences', NOW()),
('LOP',19, 'Entertainment District', 'NO', 'Location Preferences', NOW()),
('LOP',21, 'Shopping District', 'NO', 'Location Preferences', NOW()),
('LOP',23, 'Countryside', 'NO', 'Location Preferences', NOW()),
('LOP',24, 'Bay', 'NO', 'Location Preferences', NOW()),
('LOP',25, 'Marina', 'NO', 'Location Preferences', NOW()),
('LOP',26, 'Park', 'NO', 'Location Preferences', NOW()),
('LOP',27, 'River', 'NO', 'Location Preferences', NOW()),
('MPP',0, 'Meal Plan Type', 'NO', 'Meal Plan Preferences', NOW()),
('MPP',1, 'All Inclusive', 'NO', 'Meal Plan Preferences', NOW()),
('MPP',3, 'Bed & Breakfast', 'NO', 'Meal Plan Preferences', NOW()),
('MPP',10, 'Full Board', 'NO', 'Meal Plan Preferences', NOW()),
('MPP',12, 'Half Board', 'NO', 'Meal Plan Preferences', NOW()),
('MPP',14, 'Room Only', 'NO', 'Meal Plan Preferences', NOW()),
('MPP',15, 'Self Catering', 'NO', 'Meal Plan Preferences', NOW()),
('MPP',17, 'Dinner Bed & Breakfast', 'NO', 'Meal Plan Preferences', NOW()),
('PCP',0, 'Property Preferences', 'RZ', 'Accommodation Preferences', NOW()),
('PCP',2, 'All-Inclusive Resort', 'NO', 'Accommodation Preferences', NOW()),
('PCP',3, 'Apartment', 'NO', 'Accommodation Preferences', NOW()),
('PCP',4, 'Bed & Breakfast', 'RZ', 'Accommodation Preferences', NOW()),
('PCP',5, 'Cabin or Bungalow', 'NO', 'Accommodation Preferences', NOW()),
('PCP',6, 'Campground', 'NO', 'Accommodation Preferences', NOW()),
('PCP',7, 'Chalet', 'NO', 'Accommodation Preferences', NOW()),
('PCP',8, 'Condominium', 'NO', 'Accommodation Preferences', NOW()),
('PCP',15, 'Guest Farm', 'NO', 'Accommodation Preferences', NOW()),
('PCP',16, 'Guesthouse', 'RZ', 'Accommodation Preferences', NOW()),
('PCP',17, 'Health Spa', 'NO', 'Accommodation Preferences', NOW()),
('PCP',18, 'Holiday Resort', 'NO', 'Accommodation Preferences', NOW()),
('PCP',19, 'Hostel', 'NO', 'Accommodation Preferences', NOW()),
('PCP',20, 'Hotel', 'NO', 'Accommodation Preferences', NOW()),
('PCP',21, 'Inn', 'NO', 'Accommodation Preferences', NOW()),
('PCP',22, 'Lodge', 'NO', 'Accommodation Preferences', NOW()),
('PCP',25, 'Mobile Home', 'NO', 'Accommodation Preferences', NOW()),
('PCP',26, 'Monastery', 'NO', 'Accommodation Preferences', NOW()),
('PCP',27, 'Motel', 'NO', 'Accommodation Preferences', NOW()),
('PCP',28, 'Ranch', 'NO', 'Accommodation Preferences', NOW()),
('PCP',30, 'Resort', 'NO', 'Accommodation Preferences', NOW()),
('PCP',33, 'Tent', 'NO', 'Accommodation Preferences', NOW()),
('PCP',34, 'Vacation Rental', 'RZ', 'Accommodation Preferences', NOW()),
('PCP',35, 'Villa', 'NO', 'Accommodation Preferences', NOW()),
('PCP',36, 'Wildlife Reserve', 'NO', 'Accommodation Preferences', NOW()),
('PCP',37, 'Castle', 'NO', 'Accommodation Preferences', NOW()),
('PCP',40, 'Pension', 'NO', 'Accommodation Preferences', NOW()),
('PCP',43, 'Time Share', 'NO', 'Accommodation Preferences', NOW()),
('PCP',44, 'Boatel', 'NO', 'Accommodation Preferences', NOW()),
('PCP',45, 'Boutique Hotel', 'RZ', 'Accommodation Preferences', NOW()),
('PCP',50, 'Recreational Vehicle Park', 'NO', 'Accommodation Preferences', NOW()),
('PCP',52, 'Manor', 'NO', 'Accommodation Preferences', NOW()),
('PEP',0, 'Travel with Pets', 'RZ', 'Pet Preferences', NOW()),
('PEP',1, 'Cat', 'RZ', 'Pet Preferences', NOW()),
('PEP',2, 'Dog', 'RZ', 'Pet Preferences', NOW()),
('PEP',3, 'Large Animal', 'RZ', 'Pet Preferences', NOW()),
('PEP',4, 'Midsize Animal', 'RZ', 'Pet Preferences', NOW()),
('PEP',8, 'Small Animal', 'RZ', 'Pet Preferences', NOW()),
('PEP',9, 'Working Animal', 'RZ', 'Pet Preferences', NOW()),
('PHP',0, 'Physically Challenged Requirement', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',1, 'ADA Compliance', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',2, 'Audible Alarm', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',3, 'Vanity Accessible', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',4, 'Bed For Wheelchair', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',5, 'Closet Rods', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',7, 'Kitchen Accessible', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',8, 'Parking Accessible', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',12, 'Braille Information', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',13, 'Flashing Door Knocker', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',15, 'Light Switch Accessible', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',20, 'Roll-in Shower', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',21, 'Bath Accessible', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',24, 'Wheelchair Accessible', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',26, 'Peephole In Door', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',29, 'Service Animals Allowed', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',30, 'Thermostat Accessible', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',32, 'Toilet Accessible', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',33, 'Vibrating Alarm', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',34, 'Visual Alarm', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',36, 'Wheelchair Available', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',38, 'Bath Grab Bars', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',39, 'Phone For Impaired', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',42, 'Wheelchair Elevator', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',44, 'Bath Seat', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',45, 'TV W/Subtitles', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',46, 'Shower Safety Bars', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',47, 'TV W/Amplifier', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',48, 'Walk-in Shower', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',49, 'Ramp Access', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',50, 'Handicap Parking', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',52, 'Toilet Grab Bars', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',53, 'Doors Open Out', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',54, 'Bath In Bedroom', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',55, 'Elevator Accessible', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',56, 'Elevator Near Room', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',57, 'Alarm In Bathroom', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',58, 'Alarm In Bedroom', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',61, 'Facilities For Blind', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',62, 'Facilities For Deaf', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',63, 'Feather Free Beds', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',64, 'Entrance Accessible', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',65, 'Hearing Aid Loop ', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',66, 'Braille Menus', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',67, 'Large Print Menus', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',68, 'Roll-in Shower', 'RZ', 'Physically Challenged Requirements', NOW()),
('PHP',70, 'Sign Language Staff', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',71, 'Trained Staff', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',72, 'Steps with Handrails', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',73, 'Steps with Markings', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',74, 'Subtitles On TV', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',75, 'Large Print Signs', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',76, 'Vibrating Pillows', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',102, 'Bath Accessible', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',103, 'Large Print Information', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',106, 'Special Menus', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',107, 'Wide Entrance', 'NO', 'Physically Challenged Requirements', NOW()),
('PHP',108, 'Wide Corridors', 'NO', 'Physically Challenged Requirements', NOW()),
('REP',0, 'Restaurant Preferences', 'NO', 'Resturant Preferences', NOW()),
('REP',1, 'All Purpose', 'NO', 'Resturant Preferences', NOW()),
('REP',2, 'Alchoholic Beverage', 'NO', 'Resturant Preferences', NOW()),
('REP',3, 'Buffet Table', 'NO', 'Resturant Preferences', NOW()),
('REP',4, 'Cafe', 'NO', 'Resturant Preferences', NOW()),
('REP',5, 'Cafeteria', 'NO', 'Resturant Preferences', NOW()),
('REP',6, 'Casual Eating', 'NO', 'Resturant Preferences', NOW()),
('REP',7, 'Family Restaurant', 'NO', 'Resturant Preferences', NOW()),
('REP',8, 'Fast Food', 'NO', 'Resturant Preferences', NOW()),
('REP',9, 'Fine Dining', 'NO', 'Resturant Preferences', NOW()),
('REP',11, 'Take Away', 'NO', 'Resturant Preferences', NOW()),
('REP',13, 'Bar Lounge', 'NO', 'Resturant Preferences', NOW()),
('REP',14, 'Brasserie', 'NO', 'Resturant Preferences', NOW()),
('REP',15, 'Coffee Bar', 'NO', 'Resturant Preferences', NOW()),
('REP',16, 'Snack Bar', 'NO', 'Resturant Preferences', NOW()),
('REP',17, 'Full Service', 'NO', 'Resturant Preferences', NOW()),
('REP',18, 'Public Bar', 'NO', 'Resturant Preferences', NOW()),
('REP',19, 'Delicatessen', 'NO', 'Resturant Preferences', NOW()),
('RMP',0, 'Amenity Preferences', 'RZ', 'Amenity Preferences', NOW()),
('RMP',2, 'Air Conditioning', 'RZ', 'Amenity Preferences', NOW()),
('RMP',3, 'Alarm Clock', 'NO', 'Amenity Preferences', NOW()),
('RMP',5, 'AM/FM Radio', 'NO', 'Amenity Preferences', NOW()),
('RMP',7, 'Balcony/Terrace', 'NO', 'Amenity Preferences', NOW()),
('RMP',10, 'Bathrobe', 'NO', 'Amenity Preferences', NOW()),
('RMP',13, 'Bathtub', 'NO', 'Amenity Preferences', NOW()),
('RMP',16, 'Bidet', 'NO', 'Amenity Preferences', NOW()),
('RMP',19, 'Coffee/Tea Maker', 'NO', 'Amenity Preferences', NOW()),
('RMP',21, 'Computer', 'NO', 'Amenity Preferences', NOW()),
('RMP',23, 'Plug Adaptors', 'NO', 'Amenity Preferences', NOW()),
('RMP',26, 'Crib/Cot', 'NO', 'Amenity Preferences', NOW()),
('RMP',28, 'Desk', 'NO', 'Amenity Preferences', NOW()),
('RMP',32, 'Dishwasher', 'NO', 'Amenity Preferences', NOW()),
('RMP',41, 'Fireplace', 'NO', 'Amenity Preferences', NOW()),
('RMP',46, 'Free Movies/Video', 'NO', 'Amenity Preferences', NOW()),
('RMP',50, 'Hairdryer', 'NO', 'Amenity Preferences', NOW()),
('RMP',54, 'Internet Access', 'RZ', 'Amenity Preferences', NOW()),
('RMP',55, 'Iron', 'NO', 'Amenity Preferences', NOW()),
('RMP',56, 'Ironing Board', 'NO', 'Amenity Preferences', NOW()),
('RMP',57, 'Jacuzzi', 'RZ', 'Amenity Preferences', NOW()),
('RMP',59, 'Kitchen', 'NO', 'Amenity Preferences', NOW()),
('RMP',60, 'Kitchen Supplies', 'NO', 'Amenity Preferences', NOW()),
('RMP',61, 'Kitchenette', 'NO', 'Amenity Preferences', NOW()),
('RMP',68, 'Microwave', 'NO', 'Amenity Preferences', NOW()),
('RMP',69, 'Minibar', 'NO', 'Amenity Preferences', NOW()),
('RMP',74, 'Non-smoking', 'RZ', 'Amenity Preferences', NOW()),
('RMP',77, 'Oven', 'NO', 'Amenity Preferences', NOW()),
('RMP',81, 'Plates And Bowls', 'NO', 'Amenity Preferences', NOW()),
('RMP',82, 'Pots And Pans', 'NO', 'Amenity Preferences', NOW()),
('RMP',85, 'Private Bathroom', 'RZ', 'Amenity Preferences', NOW()),
('RMP',88, 'Refrigerator', 'NO', 'Amenity Preferences', NOW()),
('RMP',89, 'Refrigerator W/Icemaker', 'NO', 'Amenity Preferences', NOW()),
('RMP',90, 'TV', 'RZ', 'Amenity Preferences', NOW()),
('RMP',92, 'Safe', 'RZ', 'Amenity Preferences', NOW()),
('RMP',94, 'Separate Closet', 'NO', 'Amenity Preferences', NOW()),
('RMP',97, 'Shower Only', 'NO', 'Amenity Preferences', NOW()),
('RMP',98, 'Silverware/utensils', 'NO', 'Amenity Preferences', NOW()),
('RMP',99, 'Sitting Area', 'NO', 'Amenity Preferences', NOW()),
('RMP',100, 'Smoke Detectors', 'NO', 'Amenity Preferences', NOW()),
('RMP',101, 'Smoking', 'RZ', 'Amenity Preferences', NOW()),
('RMP',104, 'Stereo', 'NO', 'Amenity Preferences', NOW()),
('RMP',105, 'Stove', 'NO', 'Amenity Preferences', NOW()),
('RMP',107, 'Telephone', 'NO', 'Amenity Preferences', NOW()),
('RMP',120, 'Water Closet', 'NO', 'Amenity Preferences', NOW()),
('RMP',121, 'Water Filter', 'NO', 'Amenity Preferences', NOW()),
('RMP',123, 'Wireless Internet', 'NO', 'Amenity Preferences', NOW()),
('RMP',127, 'Bathtub & Jacuzzi', 'NO', 'Amenity Preferences', NOW()),
('RMP',129, 'CD Player', 'NO', 'Amenity Preferences', NOW()),
('RMP',132, 'Down/Feather Pillows', 'NO', 'Amenity Preferences', NOW()),
('RMP',135, 'Foam Pillows', 'NO', 'Amenity Preferences', NOW()),
('RMP',141, 'Bathtub Oversize', 'NO', 'Amenity Preferences', NOW()),
('RMP',142, 'Shower', 'NO', 'Amenity Preferences', NOW()),
('RMP',144, 'Soundproofed Room', 'NO', 'Amenity Preferences', NOW()),
('RMP',145, 'Storage Space', 'NO', 'Amenity Preferences', NOW()),
('RMP',146, 'Tables And Chairs', 'NO', 'Amenity Preferences', NOW()),
('RMP',148, 'Walk-in Closet', 'NO', 'Amenity Preferences', NOW()),
('RMP',149, 'Washer/Dryer', 'NO', 'Amenity Preferences', NOW()),
('RMP',150, 'Weight Scale', 'NO', 'Amenity Preferences', NOW()),
('RMP',155, 'Bathtub & Shower', 'NO', 'Amenity Preferences', NOW()),
('RMP',157, 'Ceiling Fan', 'NO', 'Amenity Preferences', NOW()),
('RMP',159, 'Plug Adaptors', 'NO', 'Amenity Preferences', NOW()),
('RMP',163, 'DVD Player', 'NO', 'Amenity Preferences', NOW()),
('RMP',167, 'Toaster', 'NO', 'Amenity Preferences', NOW()),
('RMP',183, 'Cups/Glassware', 'NO', 'Amenity Preferences', NOW()),
('RMP',193, 'Shared Bathroom', 'NO', 'Amenity Preferences', NOW()),
('RMP',206, 'Honeymoon Suites', 'NO', 'Amenity Preferences', NOW()),
('RMP',208, 'Maid Service', 'NO', 'Amenity Preferences', NOW()),
('RMP',210, 'Satellite TV', 'RZ', 'Amenity Preferences', NOW()),
('RMP',214, 'iPod Docking Station', 'RZ', 'Amenity Preferences', NOW()),
('RMP',217, 'Satellite Radio', 'NO', 'Amenity Preferences', NOW()),
('RMP',233, 'Duvet', 'NO', 'Amenity Preferences', NOW()),
('RMP',234, 'Luxury Linen Type', 'NO', 'Amenity Preferences', NOW()),
('RMP',236, 'Pantry', 'NO', 'Amenity Preferences', NOW()),
('RMP',237, 'Dish-cleaning Supplies', 'NO', 'Amenity Preferences', NOW()),
('RMP',238, 'Double Vanity', 'NO', 'Amenity Preferences', NOW()),
('RMP',239, 'Makeup Mirror', 'NO', 'Amenity Preferences', NOW()),
('RMP',243, 'Outdoor Space', 'NO', 'Amenity Preferences', NOW()),
('RMP',245, 'Private Pool', 'RZ', 'Amenity Preferences', NOW()),
('RMP',246, 'HDTV', 'NO', 'Amenity Preferences', NOW()),
('RSN', 0, 'Destination Preferences', 'RZ', 'Preferences for destinations', NOW()),
('RSN', 1, 'Beach / Sun', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 2, 'Theme / Amusement Park', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 3, 'Business Meeting / Event', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 4, 'Great Food / Wine', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 5, 'Golf', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 6, 'Skiing / Winter Sports', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 7, 'Concert / Music Festivals', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 8, 'Museum / Cultural / Historical', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 9, 'Gambling / Casinos', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 10, 'Outdoor / Adventure', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 11, 'Shopping / Fashion', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 12, 'Spa / Health', 'RZ', 'Guest reason for travel', NOW()),
('RSN', 13, 'Sporting Events', 'RZ', 'Guest reason for travel', NOW()),
('RSP',0, 'Recreation Preference', 'RZ', 'Recreation Preferences', NOW()),
('RSP',1, 'Archery', 'NO', 'Recreation Preferences', NOW()),
('RSP',2, 'Badminton', 'NO', 'Recreation Preferences', NOW()),
('RSP',3, 'Baseball', 'RZ', 'Recreation Preferences', NOW()),
('RSP',4, 'Basketball ', 'RZ', 'Recreation Preferences', NOW()),
('RSP',5, 'Beach', 'RZ', 'Recreation Preferences', NOW()),
('RSP',6, 'Bike Trail', 'RZ', 'Recreation Preferences', NOW()),
('RSP',7, 'Boating', 'RZ', 'Recreation Preferences', NOW()),
('RSP',8, 'Bocci Court', 'NO', 'Recreation Preferences', NOW()),
('RSP',9, 'Bowling Alley', 'NO', 'Recreation Preferences', NOW()),
('RSP',12, 'Cricket ', 'RZ', 'Recreation Preferences', NOW()),
('RSP',14, 'Dart Board', 'NO', 'Recreation Preferences', NOW()),
('RSP',18, 'Downhill Skiing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',20, 'Fishing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',21, 'Fitness Center', 'NO', 'Recreation Preferences', NOW()),
('RSP',25, 'Fly Fishing', 'NO', 'Recreation Preferences', NOW()),
('RSP',26, 'Football ', 'RZ', 'Recreation Preferences', NOW()),
('RSP',27, 'Golf', 'RZ', 'Recreation Preferences', NOW()),
('RSP',35, 'Gym', 'RZ', 'Recreation Preferences', NOW()),
('RSP',36, 'Health Club', 'NO', 'Recreation Preferences', NOW()),
('RSP',60, 'Hiking Trail', 'RZ', 'Recreation Preferences', NOW()),
('RSP',61, 'Horse Riding', 'RZ', 'Recreation Preferences', NOW()),
('RSP',62, 'Indoor Tennis', 'NO', 'Recreation Preferences', NOW()),
('RSP',63, 'Jet-ski', 'RZ', 'Recreation Preferences', NOW()),
('RSP',64, 'Jogging Trail', 'NO', 'Recreation Preferences', NOW()),
('RSP',65, 'Kayaking', 'RZ', 'Recreation Preferences', NOW()),
('RSP',66, 'Lake', 'NO', 'Recreation Preferences', NOW()),
('RSP',67, 'Miniature Golf', 'NO', 'Recreation Preferences', NOW()),
('RSP',68, 'Mountain Biking', 'RZ', 'Recreation Preferences', NOW()),
('RSP',70, 'Ocean', 'NO', 'Recreation Preferences', NOW()),
('RSP',71, 'Outdoor Tennis', 'NO', 'Recreation Preferences', NOW()),
('RSP',73, 'Parasailing', 'NO', 'Recreation Preferences', NOW()),
('RSP',74, 'Playground', 'RZ', 'Recreation Preferences', NOW()),
('RSP',75, 'Pool', 'NO', 'Recreation Preferences', NOW()),
('RSP',76, 'Putt Putt Golf', 'NO', 'Recreation Preferences', NOW()),
('RSP',77, 'Racquetball ', 'RZ', 'Recreation Preferences', NOW()),
('RSP',78, 'River', 'NO', 'Recreation Preferences', NOW()),
('RSP',79, 'River Rafting', 'RZ', 'Recreation Preferences', NOW()),
('RSP',80, 'Sailing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',81, 'Sauna', 'NO', 'Recreation Preferences', NOW()),
('RSP',82, 'Scuba Diving', 'RZ', 'Recreation Preferences', NOW()),
('RSP',83, 'Shopping', 'NO', 'Recreation Preferences', NOW()),
('RSP',84, 'Skating Rink', 'NO', 'Recreation Preferences', NOW()),
('RSP',85, 'Skeet Shooting', 'NO', 'Recreation Preferences', NOW()),
('RSP',86, 'Snorkeling', 'RZ', 'Recreation Preferences', NOW()),
('RSP',87, 'Snow Boarding', 'RZ', 'Recreation Preferences', NOW()),
('RSP',88, 'Snow Skiing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',89, 'Soccer Field', 'NO', 'Recreation Preferences', NOW()),
('RSP',90, 'Solarium', 'NO', 'Recreation Preferences', NOW()),
('RSP',91, 'Spa', 'NO', 'Recreation Preferences', NOW()),
('RSP',92, 'Squash Court', 'RZ', 'Recreation Preferences', NOW()),
('RSP',93, 'Steam Bath', 'NO', 'Recreation Preferences', NOW()),
('RSP',94, 'Tennis Court', 'RZ', 'Recreation Preferences', NOW()),
('RSP',96, 'Tubing', 'NO', 'Recreation Preferences', NOW()),
('RSP',97, 'Velodrome', 'NO', 'Recreation Preferences', NOW()),
('RSP',98, 'Volleyball', 'NO', 'Recreation Preferences', NOW()),
('RSP',99, 'Water-skiing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',100, 'Whirlpool', 'NO', 'Recreation Preferences', NOW()),
('RSP',101, 'Windsurfing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',102, 'Driving Range', 'NO', 'Recreation Preferences', NOW()),
('RSP',103, 'Camping', 'NO', 'Recreation Preferences', NOW()),
('RSP',104, 'Hot Tub', 'NO', 'Recreation Preferences', NOW()),
('RSP',105, 'Hunting', 'RZ', 'Recreation Preferences', NOW()),
('RSP',106, 'Swimming Pool', 'NO', 'Recreation Preferences', NOW()),
('RSP',107, 'Jacuzzi', 'NO', 'Recreation Preferences', NOW()),
('RSP',108, 'Mountain Climbing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',109, 'Nature Reserve Trail', 'NO', 'Recreation Preferences', NOW()),
('RSP',111, 'Billiards', 'NO', 'Recreation Preferences', NOW()),
('RSP',112, 'Rock Climbing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',113, 'Safari', 'RZ', 'Recreation Preferences', NOW()),
('RSP',116, 'Surfing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',117, 'Table Tennis', 'NO', 'Recreation Preferences', NOW()),
('RSP',118, 'Wine Tasting', 'RZ', 'Recreation Preferences', NOW()),
('RSP',119, 'Winter Sports', 'NO', 'Recreation Preferences', NOW()),
('RSP',120, 'Snow Mobiling', 'NO', 'Recreation Preferences', NOW()),
('RSP',122, 'Indoor Pool', 'NO', 'Recreation Preferences', NOW()),
('RSP',123, 'Outdoor Pool', 'NO', 'Recreation Preferences', NOW()),
('RSP',126, 'Animal Watching', 'NO', 'Recreation Preferences', NOW()),
('RSP',127, 'Bird Watching', 'RZ', 'Recreation Preferences', NOW()),
('RSP',128, 'Boxing', 'NO', 'Recreation Preferences', NOW()),
('RSP',129, 'Childrens Pool', 'NO', 'Recreation Preferences', NOW()),
('RSP',130, 'Dancing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',131, 'Dog Racing', 'NO', 'Recreation Preferences', NOW()),
('RSP',132, 'Fine Dining', 'RZ', 'Recreation Preferences', NOW()),
('RSP',133, 'Gambling', 'RZ', 'Recreation Preferences', NOW()),
('RSP',134, 'Garden', 'NO', 'Recreation Preferences', NOW()),
('RSP',135, 'Aerial Sightseeing', 'NO', 'Recreation Preferences', NOW()),
('RSP',136, 'Horse Racing', 'NO', 'Recreation Preferences', NOW()),
('RSP',137, 'Ice Skating', 'RZ', 'Recreation Preferences', NOW()),
('RSP',138, 'Karaoke', 'NO', 'Recreation Preferences', NOW()),
('RSP',139, 'Museum/Gallery', 'RZ', 'Recreation Preferences', NOW()),
('RSP',140, 'Nightclubs', 'RZ', 'Recreation Preferences', NOW()),
('RSP',141, 'Polo', 'RZ', 'Recreation Preferences', NOW()),
('RSP',142, 'Sightseeing Tours', 'NO', 'Recreation Preferences', NOW()),
('RSP',143, 'Sports Events', 'NO', 'Recreation Preferences', NOW()),
('RSP',144, 'Skydiving', 'RZ', 'Recreation Preferences', NOW()),
('RSP',145, 'Sunbathing', 'RZ', 'Recreation Preferences', NOW()),
('RSP',146, 'Theatre', 'RZ', 'Recreation Preferences', NOW()),
('RSP',147, 'Weightlifting', 'NO', 'Recreation Preferences', NOW()),
('RSP',148, 'Wrestling', 'NO', 'Recreation Preferences', NOW()),
('RSP',149, 'Canoeing', 'NO', 'Recreation Preferences', NOW()),
('RSP',150, 'Upscale Shopping', 'NO', 'Recreation Preferences', NOW()),
('RSP',151, 'Outlet Shopping', 'NO', 'Recreation Preferences', NOW()),
('RSP',152, 'Antique Shopping', 'NO', 'Recreation Preferences', NOW()),
('RSP',154, 'Bocce Court', 'NO', 'Recreation Preferences', NOW()),
('RSP',155, 'Direct Access To Beach', 'NO', 'Recreation Preferences', NOW()),
('SEP',0, 'Security Requirement', 'NO', 'Security Requirements', NOW()),
('SEP',3, 'Alarm Monitored', 'NO', 'Security Requirements', NOW()),
('SEP',7, 'Building Code Compliant', 'NO', 'Security Requirements', NOW()),
('SEP',8, 'Safety Act Compliant', 'NO', 'Security Requirements', NOW()),
('SEP',9, 'Fire Law Compliant', 'NO', 'Security Requirements', NOW()),
('SEP',10, 'Door Dead Bolt', 'NO', 'Security Requirements', NOW()),
('SEP',12, 'Doctor on Call', 'NO', 'Security Requirements', NOW()),
('SEP',13, 'Electronic Key', 'NO', 'Security Requirements', NOW()),
('SEP',15, 'Emergency Generator', 'NO', 'Security Requirements', NOW()),
('SEP',16, 'Evacuation Plan', 'NO', 'Security Requirements', NOW()),
('SEP',18, 'Emergency Info ', 'NO', 'Security Requirements', NOW()),
('SEP',19, 'Emergency Lights', 'NO', 'Security Requirements', NOW()),
('SEP',20, 'Fire Detectors', 'NO', 'Security Requirements', NOW()),
('SEP',23, 'Fire Extinguishers', 'NO', 'Security Requirements', NOW()),
('SEP',24, 'Fire Resistant Doors', 'NO', 'Security Requirements', NOW()),
('SEP',28, 'Smoke Detectors', 'NO', 'Security Requirements', NOW()),
('SEP',30, 'Lighted Parking', 'NO', 'Security Requirements', NOW()),
('SEP',31, 'Lighted Walkways', 'NO', 'Security Requirements', NOW()),
('SEP',32, 'Multiple Exits', 'NO', 'Security Requirements', NOW()),
('SEP',34, 'Patrolled Parking', 'NO', 'Security Requirements', NOW()),
('SEP',37, 'PA System', 'NO', 'Security Requirements', NOW()),
('SEP',39, 'No Public Access', 'NO', 'Security Requirements', NOW()),
('SEP',42, 'No Sliding Glass Doors', 'NO', 'Security Requirements', NOW()),
('SEP',44, 'Door Safety Chains', 'NO', 'Security Requirements', NOW()),
('SEP',47, '24 h Security', 'NO', 'Security Requirements', NOW()),
('SEP',52, 'Sprinklers', 'NO', 'Security Requirements', NOW()),
('SEP',57, 'First Aid Personnel', 'NO', 'Security Requirements', NOW()),
('SEP',63, 'Viewports In Doors', 'NO', 'Security Requirements', NOW()),
('SEP',65, 'Lighted Exit Signs', 'NO', 'Security Requirements', NOW()),
('SEP',78, 'Parking Access Control', 'NO', 'Security Requirements', NOW()),
('SEP',86, '24h CCTV Surveillance', 'NO', 'Security Requirements', NOW()),
('SEP',90, 'First Aid Kit', 'NO', 'Security Requirements', NOW())