//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 12:35:34 PM IST 
//


package net.cbtltd.rest.hotelscombined.roomrates.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.cbtltd.rest.hotelscombined.roomrates.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.cbtltd.rest.hotelscombined.roomrates.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OTAHotelAvailRQ }
     * 
     */
    public OTAHotelAvailRQ createOTAHotelAvailRQ() {
        return new OTAHotelAvailRQ();
    }

    /**
     * Create an instance of {@link OTAHotelAvailRQ.AvailRequestSegments }
     * 
     */
    public OTAHotelAvailRQ.AvailRequestSegments createOTAHotelAvailRQAvailRequestSegments() {
        return new OTAHotelAvailRQ.AvailRequestSegments();
    }

    /**
     * Create an instance of {@link OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment }
     * 
     */
    public OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment createOTAHotelAvailRQAvailRequestSegmentsAvailRequestSegment() {
        return new OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment();
    }

    /**
     * Create an instance of {@link OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria }
     * 
     */
    public OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria createOTAHotelAvailRQAvailRequestSegmentsAvailRequestSegmentHotelSearchCriteria() {
        return new OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria();
    }

    /**
     * Create an instance of {@link OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria.Criterion }
     * 
     */
    public OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria.Criterion createOTAHotelAvailRQAvailRequestSegmentsAvailRequestSegmentHotelSearchCriteriaCriterion() {
        return new OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria.Criterion();
    }

    /**
     * Create an instance of {@link OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria.Criterion.HotelRef }
     * 
     */
    public OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria.Criterion.HotelRef createOTAHotelAvailRQAvailRequestSegmentsAvailRequestSegmentHotelSearchCriteriaCriterionHotelRef() {
        return new OTAHotelAvailRQ.AvailRequestSegments.AvailRequestSegment.HotelSearchCriteria.Criterion.HotelRef();
    }

}
