/**
 * @author	abookingnet
 * @see License at http://abookingnet.com
 * @version	4.0.0
 */
package net.cbtltd.shared;

public enum Method {
	BALANCE, QUANTITY, MONTHCHART, YEARCHART, ENTITYTYPE,
	ATTRIBUTE, ARCHIVE, CREATE, DELETE, EXISTS, ITEMTABLE, NAME, READ, UPDATE, WRITE,
	AGENTCREATE, AGENTSCREATE, AGENTDELETE, AGENTSDELETE, ORGANIZATIONCREATE,
	COUNTRYNAME, CURRENCYNAME, DEPRECIATIONNAME, NEARBYNAME, REGIONNAME,
	MARKETREGION, MARKETLOCATION, MARKETREAD, POSITION,
	AUTOLOGIN, LOGIN, LOGOUT, PASSWORDCREATE, PASSWORDUPDATE};
