package net.cbtltd.rest.maxxton;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2014-12-01T12:16:43.313+01:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", name = "NewyseWebService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface NewyseWebService {

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public WorkOrderAreaContainer getWorkOrderAreas(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        WorkOrderAreaCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public CustomerTitleContainer getCustomerTitles(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        CustomerTitleCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public WorkOrderCategoryContainer getWorkOrderCategories(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        WorkOrderCategoryCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public AccommodationTypeContainer getAccommodationTypes(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        AccommodationTypeCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public Reservation confirmReservation(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ReservationCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ResortContainer getResorts(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ResortCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public WorkOrderItemContainer getWorkOrderItems(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        WorkOrderItemCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public Reservation createReservationProposal(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ReservationCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public DebitCardItemContainer getDebitCardItems(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        DebitCardItemCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ObjectContainer getObjects(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ObjectCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ResourceCapacityContainer getResourceCapacity(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ResourceCapacityCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ObjectAvailabilityContainer getObjectAvailability(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ObjectAvailabilityCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public BrochureContainer getBrochures(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        BrochureCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public WorkOrder createWorkOrder(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "WorkOrder", name = "WorkOrder")
        WorkOrder workOrder
    ) throws NewyseWebserviceException;

    @WebMethod
    public void updateDebitCardItems(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "DebitCardTransactionContainer", name = "DebitCardTransactionContainer")
        DebitCardTransactionContainer debitCardTransactionContainer
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ReservationSubjectContainer getReservationSubjects(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ReservationSubjectCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public DebitCardCustomerInfoContainer getDebitCardCustomersInfo(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "DebitCardNumber", name = "DebitCardNumber")
        java.lang.String debitCardNumber
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public AccommodationTypeSearchContainer findAccommodationTypes(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        AccommodationTypeSearchCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ReservedResourceContainer addResource(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "ReservationId", name = "ReservationId")
        long reservationId,
        @WebParam(partName = "Criteria", name = "Criteria")
        ResourceCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ReservationContainer declineReservation(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        GetReservation criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ReservationContainer getReservation(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        GetReservation criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public CountryContainer getCountries(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public KCPincodes getKCActiveDoorlockPincodes(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "StartDate", name = "StartDate")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(partName = "EndDate", name = "EndDate")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(partName = "ResortCode", name = "ResortCode")
        java.lang.String resortCode
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public PropertyContainer getProperties(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        PropertyCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public VoucherContainer generateVouchers(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        VoucherCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public DebitCardCustomerContainer getDebitCardCustomers(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "DebitCardNumber", name = "DebitCardNumber")
        java.lang.String debitCardNumber
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public Payment registerPayment(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        PaymentCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ResourceAdditionContainer getResourceAdditions(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ResourceAdditionCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public SubjectContainer getSubjects(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        SubjectCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public SourceContainer getSources(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        SourceCriteria criteria
    ) throws NewyseWebserviceException;

    @WebMethod
    public void updateCustomer(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Customer", name = "Customer")
        Customer customer
    ) throws NewyseWebserviceException;

    @WebMethod
    public void requestBrochures(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "BrochureRequest", name = "BrochureRequest")
        BrochureRequest brochureRequest
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ImageContainer getImages(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ImageCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public Address getAddress(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        AddressCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public AccommodationKindContainer getAccommodationKinds(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        AccommodationKindCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public AvailabilityContainer getResourceAvailability(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        AvailabilityCriteria criteria
    ) throws NewyseWebserviceException;

    @WebMethod
    public void updateReservation(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        UpdateReservationCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public KCPincodes getKCDoorlockPincodes(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "StartDate", name = "StartDate")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(partName = "EndDate", name = "EndDate")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(partName = "ResortCode", name = "ResortCode")
        java.lang.String resortCode,
        @WebParam(partName = "LockCode", name = "LockCode")
        java.lang.String lockCode
    ) throws NewyseWebserviceException;

    @WebMethod
    public void destroySession(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ReservationContainer cancelReservation(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        GetReservation criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public java.lang.String getInfo() throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public Customer createCustomer(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Customer", name = "Customer")
        Customer customer
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public TipTripCategoryContainer getTipTripCategories(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        TipTripCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public FacilityContainer getFacilities(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        FacilityCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ReservedResourceContainer getReservedResources(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ReservedResourceCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ResortActivityContainer getResortActivities(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        ResortActivityCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public Reservation registerKCDoorlockPincodeEvent(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "PincodeRegistration", name = "PincodeRegistration")
        PincodeRegistration pincodeRegistration
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public ReservationContainer checkinReservation(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        GetReservation criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public TipTripContainer getTipTrips(
        @WebParam(partName = "SessionKey", name = "SessionKey")
        java.lang.String sessionKey,
        @WebParam(partName = "Criteria", name = "Criteria")
        TipTripCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public java.lang.String createSession(
        @WebParam(partName = "Criteria", name = "Criteria")
        SessionCriteria criteria
    ) throws NewyseWebserviceException;

    @WebResult(name = "return", targetNamespace = "http://service.newyse.ws.services.newyse.maxxton/", partName = "return")
    @WebMethod
    public DebitCardContainer getActiveDebitCardForReservation(
        @WebParam(partName = "Sessionkey", name = "Sessionkey")
        java.lang.String sessionkey,
        @WebParam(partName = "Criteria", name = "Criteria")
        DebitCardCriteria criteria
    ) throws NewyseWebserviceException;
}
