package net.cbtltd.rest.leisurelink.ExternalServices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-10-17T09:48:55.473+02:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "DistributionServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface DistributionServiceSoap {

    @WebResult(name = "GetDistributionPropertesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDistributionPropertes", targetNamespace = "http://tempuri.org/", className = "net.cbtltd.rest.leisurelink.GetDistributionPropertes")
    @WebMethod(operationName = "GetDistributionPropertes", action = "http://tempuri.org/GetDistributionPropertes")
    @ResponseWrapper(localName = "GetDistributionPropertesResponse", targetNamespace = "http://tempuri.org/", className = "net.cbtltd.rest.leisurelink.GetDistributionPropertesResponse")
    public net.cbtltd.rest.leisurelink.ExternalServices.ArrayOfDistributionProperty getDistributionPropertes(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        java.lang.String account,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebResult(name = "GetRatesAndAvailabiltyUpdatedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRatesAndAvailabiltyUpdated", targetNamespace = "http://tempuri.org/", className = "net.cbtltd.rest.leisurelink.GetRatesAndAvailabiltyUpdated")
    @WebMethod(operationName = "GetRatesAndAvailabiltyUpdated", action = "http://tempuri.org/GetRatesAndAvailabiltyUpdated")
    @ResponseWrapper(localName = "GetRatesAndAvailabiltyUpdatedResponse", targetNamespace = "http://tempuri.org/", className = "net.cbtltd.rest.leisurelink.GetRatesAndAvailabiltyUpdatedResponse")
    public net.cbtltd.rest.leisurelink.ExternalServices.RateAvailabilityUpdateRQ getRatesAndAvailabiltyUpdated(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        java.lang.String account,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "PropertyCode", targetNamespace = "http://tempuri.org/")
        java.lang.String propertyCode,
        @WebParam(name = "BeginDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(name = "UpdatedSince", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar updatedSince
    );

    @WebResult(name = "GetRatesAndAvailabiltyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRatesAndAvailabilty", targetNamespace = "http://tempuri.org/", className = "net.cbtltd.rest.leisurelink.GetRatesAndAvailabilty")
    @WebMethod(operationName = "GetRatesAndAvailabilty", action = "http://tempuri.org/GetRatesAndAvailabilty")
    @ResponseWrapper(localName = "GetRatesAndAvailabiltyResponse", targetNamespace = "http://tempuri.org/", className = "net.cbtltd.rest.leisurelink.GetRatesAndAvailabiltyResponse")
    public net.cbtltd.rest.leisurelink.ExternalServices.RateAvailabilityUpdateRQ getRatesAndAvailabilty(
        @WebParam(name = "Account", targetNamespace = "http://tempuri.org/")
        java.lang.String account,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "PropertyCode", targetNamespace = "http://tempuri.org/")
        java.lang.String propertyCode,
        @WebParam(name = "BeginDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar endDate
    );
}
