//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 11:17:36 AM IST 
//


package net.cbtltd.rest.hotelscombined.rates.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.cbtltd.rest.hotelscombined.rates.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.cbtltd.rest.hotelscombined.rates.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OTAHotelRateAmountNotifRQ }
     * 
     */
    public OTAHotelRateAmountNotifRQ createOTAHotelRateAmountNotifRQ() {
        return new OTAHotelRateAmountNotifRQ();
    }

    /**
     * Create an instance of {@link OTAHotelRateAmountNotifRQ.RateAmountMessages }
     * 
     */
    public OTAHotelRateAmountNotifRQ.RateAmountMessages createOTAHotelRateAmountNotifRQRateAmountMessages() {
        return new OTAHotelRateAmountNotifRQ.RateAmountMessages();
    }

    /**
     * Create an instance of {@link OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage }
     * 
     */
    public OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage createOTAHotelRateAmountNotifRQRateAmountMessagesRateAmountMessage() {
        return new OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage();
    }

    /**
     * Create an instance of {@link OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates }
     * 
     */
    public OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates createOTAHotelRateAmountNotifRQRateAmountMessagesRateAmountMessageRates() {
        return new OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates();
    }

    /**
     * Create an instance of {@link OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate }
     * 
     */
    public OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate createOTAHotelRateAmountNotifRQRateAmountMessagesRateAmountMessageRatesRate() {
        return new OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate();
    }

    /**
     * Create an instance of {@link OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate.BaseByGuestAmts }
     * 
     */
    public OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate.BaseByGuestAmts createOTAHotelRateAmountNotifRQRateAmountMessagesRateAmountMessageRatesRateBaseByGuestAmts() {
        return new OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate.BaseByGuestAmts();
    }

    /**
     * Create an instance of {@link OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.StatusApplicationControl }
     * 
     */
    public OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.StatusApplicationControl createOTAHotelRateAmountNotifRQRateAmountMessagesRateAmountMessageStatusApplicationControl() {
        return new OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.StatusApplicationControl();
    }

    /**
     * Create an instance of {@link OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate.BaseByGuestAmts.BaseByGuestAmt }
     * 
     */
    public OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate.BaseByGuestAmts.BaseByGuestAmt createOTAHotelRateAmountNotifRQRateAmountMessagesRateAmountMessageRatesRateBaseByGuestAmtsBaseByGuestAmt() {
        return new OTAHotelRateAmountNotifRQ.RateAmountMessages.RateAmountMessage.Rates.Rate.BaseByGuestAmts.BaseByGuestAmt();
    }

    
    /**
     * Create an instance of {@link OTAHotelRatePlanRQ }
     * 
     */
    public OTAHotelRatePlanRQ createOTAHotelRatePlanRQ() {
        return new OTAHotelRatePlanRQ();
    }

    /**
     * Create an instance of {@link OTAHotelRatePlanRQ.RatePlans.RatePlan.RatePlanCandidates.RatePlanCandidate }
     * 
     */
    public OTAHotelRatePlanRQ.RatePlans.RatePlan.RatePlanCandidates.RatePlanCandidate createOTAHotelRatePlanRQRatePlansRatePlanRatePlanCandidatesRatePlanCandidate() {
        return new OTAHotelRatePlanRQ.RatePlans.RatePlan.RatePlanCandidates.RatePlanCandidate();
    }

    /**
     * Create an instance of {@link OTAHotelRatePlanRQ.RatePlans.RatePlan.DateRange }
     * 
     */
    public OTAHotelRatePlanRQ.RatePlans.RatePlan.DateRange createOTAHotelRatePlanRQRatePlansRatePlanDateRange() {
        return new OTAHotelRatePlanRQ.RatePlans.RatePlan.DateRange();
    }

    /**
     * Create an instance of {@link OTAHotelRatePlanRQ.RatePlans.RatePlan.HotelRef }
     * 
     */
    public OTAHotelRatePlanRQ.RatePlans.RatePlan.HotelRef createOTAHotelRatePlanRQRatePlansRatePlanHotelRef() {
        return new OTAHotelRatePlanRQ.RatePlans.RatePlan.HotelRef();
    }

    /**
     * Create an instance of {@link OTAHotelRatePlanRQ.RatePlans.RatePlan }
     * 
     */
    public OTAHotelRatePlanRQ.RatePlans.RatePlan createOTAHotelRatePlanRQRatePlansRatePlan() {
        return new OTAHotelRatePlanRQ.RatePlans.RatePlan();
    }

    /**
     * Create an instance of {@link OTAHotelRatePlanRQ.RatePlans }
     * 
     */
    public OTAHotelRatePlanRQ.RatePlans createOTAHotelRatePlanRQRatePlans() {
        return new OTAHotelRatePlanRQ.RatePlans();
    }

    /**
     * Create an instance of {@link OTAHotelRatePlanRQ.RatePlans.RatePlan.RatePlanCandidates }
     * 
     */
    public OTAHotelRatePlanRQ.RatePlans.RatePlan.RatePlanCandidates createOTAHotelRatePlanRQRatePlansRatePlanRatePlanCandidates() {
        return new OTAHotelRatePlanRQ.RatePlans.RatePlan.RatePlanCandidates();
    }
    
    
}
