<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:ota="http://www.opentravel.org/OTA/2003/05" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.opentravel.org/OTA/2003/05">
	
	<!-- Import Interface Definition WSDL-->
	<import namespace="http://www.opentravel.org/OTA/2003/05" location="OTA_VehResInterface.wsdl" />
	<!-- Define SOAP binding-->
	<binding name="VehicleReservationBinding" type="ota:VehicleReservationPortType">
		<!-- Use document style and not rpc-->
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/ 
soap/http" />
		<operation name="OTA_VehResRQ">
			<!-- Use 'literal' to include OTA XML as-is-->
			<soap:operation soapAction="CreateReservation" style="document" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<!-- Define SOAP interface with previously declared binding-->
	<service name="OTAVehicleReservationService">
		<port name="VehicleReservationPort" binding="ota:VehicleReservationBinding">
			<!--
				Replace "http://mydomain/myservicename" with actual service endpoint
			-->
			<soap:address location="http://mydomain/myservicename" />
		</port>
	</service>
</definitions> 