//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:35:11 PM IST 
//


package net.cbtltd.rest.flipkey.xmlfeed;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}weekend_min_rate"/>
 *         &lt;element ref="{}weeknight_max_rate"/>
 *         &lt;element ref="{}end_date"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}changeover_day"/>
 *           &lt;element ref="{}is_changeover_day_defined"/>
 *           &lt;element ref="{}min_stay_count"/>
 *           &lt;element ref="{}min_stay_unit"/>
 *           &lt;element ref="{}minimum_length"/>
 *           &lt;element ref="{}month_max_rate"/>
 *           &lt;element ref="{}month_min_rate"/>
 *           &lt;element ref="{}per_person_over_amount"/>
 *           &lt;element ref="{}per_person_per_night"/>
 *           &lt;element ref="{}per_person_per_stay"/>
 *           &lt;element ref="{}week_max_rate"/>
 *           &lt;element ref="{}week_min_rate"/>
 *           &lt;element ref="{}weekend_max_rate"/>
 *           &lt;element ref="{}weekend_nights"/>
 *           &lt;element ref="{}label"/>
 *           &lt;element ref="{}start_date"/>
 *           &lt;element ref="{}turn_day"/>
 *           &lt;element ref="{}weeknight_min_rate"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"rule",
    "weekendMinRate",
    "weeknightMaxRate",
    "endDate",
    "changeoverDayOrIsChangeoverDayDefinedOrMinStayCount"
})
@XmlRootElement(name = "property_rate")
public class PropertyRate {

    @XmlElement(name = "weekend_min_rate", required = true)
    protected String weekendMinRate;
    @XmlElement(name = "weeknight_max_rate", required = true)
    protected String weeknightMaxRate;
    @XmlElement(name = "end_date", required = true)
    protected String endDate;
    
    @XmlElement(name = "rule")
    protected String rule;
    /**
	 * @return the rule
	 */
	public String getRule() {
		return rule;
	}

	/**
	 * @param rule the rule to set
	 */
	public void setRule(String rule) {
		this.rule = rule;
	}

	@XmlElementRefs({
        @XmlElementRef(name = "per_person_per_stay", type = PerPersonPerStay.class),
        @XmlElementRef(name = "is_changeover_day_defined", type = JAXBElement.class),
        @XmlElementRef(name = "month_max_rate", type = JAXBElement.class),
        @XmlElementRef(name = "weeknight_min_rate", type = JAXBElement.class),
        @XmlElementRef(name = "week_max_rate", type = JAXBElement.class),
        @XmlElementRef(name = "start_date", type = JAXBElement.class),
        @XmlElementRef(name = "label", type = JAXBElement.class),
        @XmlElementRef(name = "changeover_day", type = JAXBElement.class),
        @XmlElementRef(name = "turn_day", type = JAXBElement.class),
        @XmlElementRef(name = "weekend_nights", type = JAXBElement.class),
        @XmlElementRef(name = "weekend_max_rate", type = JAXBElement.class),
        @XmlElementRef(name = "per_person_over_amount", type = JAXBElement.class),
        @XmlElementRef(name = "min_stay_unit", type = JAXBElement.class),
        @XmlElementRef(name = "week_min_rate", type = JAXBElement.class),
        @XmlElementRef(name = "month_min_rate", type = JAXBElement.class),
        @XmlElementRef(name = "min_stay_count", type = JAXBElement.class),
        @XmlElementRef(name = "minimum_length", type = JAXBElement.class),
        @XmlElementRef(name = "per_person_per_night", type = PerPersonPerNight.class)
    })
    protected List<Object> changeoverDayOrIsChangeoverDayDefinedOrMinStayCount;

    /**
     * Gets the value of the weekendMinRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeekendMinRate() {
        return weekendMinRate;
    }

    /**
     * Sets the value of the weekendMinRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeekendMinRate(String value) {
        this.weekendMinRate = value;
    }

    /**
     * Gets the value of the weeknightMaxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeeknightMaxRate() {
        return weeknightMaxRate;
    }

    /**
     * Sets the value of the weeknightMaxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeeknightMaxRate(String value) {
        this.weeknightMaxRate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the changeoverDayOrIsChangeoverDayDefinedOrMinStayCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the changeoverDayOrIsChangeoverDayDefinedOrMinStayCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChangeoverDayOrIsChangeoverDayDefinedOrMinStayCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PerPersonPerStay }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link PerPersonPerNight }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * 
     */
    public List<Object> getChangeoverDayOrIsChangeoverDayDefinedOrMinStayCount() {
        if (changeoverDayOrIsChangeoverDayDefinedOrMinStayCount == null) {
            changeoverDayOrIsChangeoverDayDefinedOrMinStayCount = new ArrayList<Object>();
        }
        return this.changeoverDayOrIsChangeoverDayDefinedOrMinStayCount;
    }

}
