//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.03 at 03:35:11 PM IST 
//


package net.cbtltd.rest.flipkey.xmlfeed;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}twin_count"/>
 *         &lt;element ref="{}other_count"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}standard_count"/>
 *         &lt;element ref="{}bunk_count"/>
 *         &lt;element ref="{}queen_count"/>
 *         &lt;element ref="{}king_count"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "twinCount",
    "otherCount",
    "description",
    "standardCount",
    "bunkCount",
    "queenCount",
    "kingCount"
})
@XmlRootElement(name = "property_bedroom")
public class PropertyBedroom {

    @XmlElement(name = "twin_count", required = true)
    protected String twinCount;
    @XmlElement(name = "other_count", required = true)
    protected String otherCount;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(name = "standard_count", required = true)
    protected String standardCount;
    @XmlElement(name = "bunk_count", required = true)
    protected String bunkCount;
    @XmlElement(name = "queen_count", required = true)
    protected String queenCount;
    @XmlElement(name = "king_count", required = true)
    protected String kingCount;

    /**
     * Gets the value of the twinCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTwinCount() {
        return twinCount;
    }

    /**
     * Sets the value of the twinCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTwinCount(String value) {
        this.twinCount = value;
    }

    /**
     * Gets the value of the otherCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherCount() {
        return otherCount;
    }

    /**
     * Sets the value of the otherCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherCount(String value) {
        this.otherCount = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the standardCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardCount() {
        return standardCount;
    }

    /**
     * Sets the value of the standardCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardCount(String value) {
        this.standardCount = value;
    }

    /**
     * Gets the value of the bunkCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBunkCount() {
        return bunkCount;
    }

    /**
     * Sets the value of the bunkCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBunkCount(String value) {
        this.bunkCount = value;
    }

    /**
     * Gets the value of the queenCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueenCount() {
        return queenCount;
    }

    /**
     * Sets the value of the queenCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueenCount(String value) {
        this.queenCount = value;
    }

    /**
     * Gets the value of the kingCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKingCount() {
        return kingCount;
    }

    /**
     * Sets the value of the kingCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKingCount(String value) {
        this.kingCount = value;
    }

}
