
package net.cbtltd.rest.ciirus.ciirusxmladditionalfunctions1.com.ciirus.xml;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;

import net.cbtltd.rest.ciirus.ciirusxml.com.ciirus.xml.ArrayOfCommunities;
import net.cbtltd.rest.ciirus.ciirusxml.com.ciirus.xml.ArrayOfManagementCompanies;
import net.cbtltd.rest.ciirus.ciirusxml.com.ciirus.xml.ArrayOfPropertyClasses;
import net.cbtltd.rest.ciirus.ciirusxml.com.ciirus.xml.ArrayOfReservations;
import net.cbtltd.rest.ciirus.ciirusxml.com.ciirus.xml.CiirusXMLSoap;
import net.cbtltd.rest.interhome.ArrayOfPropertyTypes;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-10-08T11:13:41.239+02:00
 * Generated source version: 2.4.0
 * 
 */
public final class Test {

    private static final QName SERVICE_NAME = new QName("http://xml.ciirus.com/", "CiirusXML");

    private Test() {
    }
    
    public static void main(String args[]) throws Exception {

    }

}
