/**
 * @author	abookingnet
 * @see License at http://abookingnet.com
 * @version	4.0.0
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.26 at 04:33:18 PM CAT 
//


package net.cbtltd.rest.ota;

import javax.xml.bind.annotation.XmlRegistry;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.cbtltd.rest.ota.type package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class FiltersRSObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.cbtltd.rest.ota.type
     * 
     */
    public FiltersRSObjectFactory() {
    }

    /**
     * Create an instance of {@link FiltersRS.FilterFields.FilterField }
     * 
     */
    public FiltersRS.FilterFields.FilterField createEResFiltersRSFilterFieldsFilterField() {
        return new FiltersRS.FilterFields.FilterField();
    }

    /**
     * Create an instance of {@link FiltersRS.FilterFields.FilterField.FilterValues.FilterValue }
     * 
     */
    public FiltersRS.FilterFields.FilterField.FilterValues.FilterValue createEResFiltersRSFilterFieldsFilterFieldFilterValuesFilterValue() {
        return new FiltersRS.FilterFields.FilterField.FilterValues.FilterValue();
    }

    /**
     * Create an instance of {@link FiltersRS.PropertyAreas }
     * 
     */
    public FiltersRS.PropertyAreas createEResFiltersRSPropertyAreas() {
        return new FiltersRS.PropertyAreas();
    }

    /**
     * Create an instance of {@link FiltersRS.PropertyAreas.PropertyArea.PropertyLocations }
     * 
     */
    public FiltersRS.PropertyAreas.PropertyArea.PropertyLocations createEResFiltersRSPropertyAreasPropertyAreaPropertyLocations() {
        return new FiltersRS.PropertyAreas.PropertyArea.PropertyLocations();
    }

    /**
     * Create an instance of {@link FiltersRS.FilterFields }
     * 
     */
    public FiltersRS.FilterFields createEResFiltersRSFilterFields() {
        return new FiltersRS.FilterFields();
    }

    /**
     * Create an instance of {@link FiltersRS.FilterFields.FilterField.FilterValues }
     * 
     */
    public FiltersRS.FilterFields.FilterField.FilterValues createEResFiltersRSFilterFieldsFilterFieldFilterValues() {
        return new FiltersRS.FilterFields.FilterField.FilterValues();
    }

    /**
     * Create an instance of {@link FiltersRS.PropertyAreas.PropertyArea }
     * 
     */
    public FiltersRS.PropertyAreas.PropertyArea createEResFiltersRSPropertyAreasPropertyArea() {
        return new FiltersRS.PropertyAreas.PropertyArea();
    }

    /**
     * Create an instance of {@link FiltersRS }
     * 
     */
    public FiltersRS createEResFiltersRS() {
        return new FiltersRS();
    }

    /**
     * Create an instance of {@link FiltersRS.PropertyAreas.PropertyArea.PropertyLocations.PropertyLocation }
     * 
     */
    public FiltersRS.PropertyAreas.PropertyArea.PropertyLocations.PropertyLocation createEResFiltersRSPropertyAreasPropertyAreaPropertyLocationsPropertyLocation() {
        return new FiltersRS.PropertyAreas.PropertyArea.PropertyLocations.PropertyLocation();
    }

}
