package net.cbtltd.rest.interhome;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2012-08-09T13:20:11.752+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://www.interhome.com/webservice", name = "WebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebServiceSoap {

    @WebResult(name = "CheckServerHealthV2Result", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CheckServerHealthV2", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CheckServerHealthV2")
    @WebMethod(operationName = "CheckServerHealthV2", action = "http://www.interhome.com/webservice/CheckServerHealthV2")
    @ResponseWrapper(localName = "CheckServerHealthV2Response", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CheckServerHealthV2Response")
    public net.cbtltd.rest.interhome.CheckServerHealthResultV2 checkServerHealthV2(
        @WebParam(name = "type", targetNamespace = "http://www.interhome.com/webservice")
        java.lang.String type
    );

    @WebResult(name = "CancelBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CancelBooking", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CancelBooking")
    @WebMethod(operationName = "CancelBooking", action = "http://www.interhome.com/webservice/CancelBooking")
    @ResponseWrapper(localName = "CancelBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CancelBookingResponse")
    public net.cbtltd.rest.interhome.CancelBookingReturnValue cancelBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.CancelBookingInputValue inputValue
    );

    @WebResult(name = "PaymentExtInformationResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "PaymentExtInformation", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.PaymentExtInformation")
    @WebMethod(operationName = "PaymentExtInformation", action = "http://www.interhome.com/webservice/PaymentExtInformation")
    @ResponseWrapper(localName = "PaymentExtInformationResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.PaymentExtInformationResponse")
    public net.cbtltd.rest.interhome.PaymentInformationReturnValue paymentExtInformation(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.PaymentInformationInputValue inputValue
    );

    @WebResult(name = "PricesResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Prices", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.Prices")
    @WebMethod(operationName = "Prices", action = "http://www.interhome.com/webservice/Prices")
    @ResponseWrapper(localName = "PricesResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.PricesResponse")
    public net.cbtltd.rest.interhome.PricesRetunValue prices(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.PricesInputValue inputValue
    );

    @WebResult(name = "NewsletterResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Newsletter", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.Newsletter")
    @WebMethod(operationName = "Newsletter", action = "http://www.interhome.com/webservice/Newsletter")
    @ResponseWrapper(localName = "NewsletterResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.NewsletterResponse")
    public net.cbtltd.rest.interhome.NewsletterReturnValue newsletter(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.NewsletterInputValue inputValue
    );

    @WebResult(name = "CheckBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CheckBooking", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CheckBooking")
    @WebMethod(operationName = "CheckBooking", action = "http://www.interhome.com/webservice/CheckBooking")
    @ResponseWrapper(localName = "CheckBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CheckBookingResponse")
    public net.cbtltd.rest.interhome.CheckBookingReturnValue checkBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.CheckBookingInputValue inputValue
    );

    @WebResult(name = "RetailerBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "RetailerBooking", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.RetailerBooking")
    @WebMethod(operationName = "RetailerBooking", action = "http://www.interhome.com/webservice/RetailerBooking")
    @ResponseWrapper(localName = "RetailerBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.RetailerBookingResponse")
    public net.cbtltd.rest.interhome.RetailerBookingReturnValue retailerBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.RetailerBookingInputValue inputValue
    );

    @WebResult(name = "NearestBookingDateResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "NearestBookingDate", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.NearestBookingDate")
    @WebMethod(operationName = "NearestBookingDate", action = "http://www.interhome.com/webservice/NearestBookingDate")
    @ResponseWrapper(localName = "NearestBookingDateResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.NearestBookingDateResponse")
    public net.cbtltd.rest.interhome.NearestBookingDateReturnValue nearestBookingDate(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.NearestBookingDateInputValue inputValue
    );

    @WebResult(name = "CheckServerHealthResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CheckServerHealth", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CheckServerHealth")
    @WebMethod(operationName = "CheckServerHealth", action = "http://www.interhome.com/webservice/CheckServerHealth")
    @ResponseWrapper(localName = "CheckServerHealthResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CheckServerHealthResponse")
    public net.cbtltd.rest.interhome.CheckServerHealthResult checkServerHealth();

    @WebResult(name = "SearchResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Search", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.Search")
    @WebMethod(operationName = "Search", action = "http://www.interhome.com/webservice/Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.SearchResponse")
    public net.cbtltd.rest.interhome.SearchReturnValue search(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.SearchInputValue inputValue
    );

    @WebResult(name = "PriceDetailResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "PriceDetail", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.PriceDetail")
    @WebMethod(operationName = "PriceDetail", action = "http://www.interhome.com/webservice/PriceDetail")
    @ResponseWrapper(localName = "PriceDetailResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.PriceDetailResponse")
    public net.cbtltd.rest.interhome.PriceDetailRetunValue priceDetail(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.PriceDetailInputValue inputValue
    );

    @WebResult(name = "AvailabilityResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Availability", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.Availability")
    @WebMethod(operationName = "Availability", action = "http://www.interhome.com/webservice/Availability")
    @ResponseWrapper(localName = "AvailabilityResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.AvailabilityResponse")
    public net.cbtltd.rest.interhome.AvailabilityRetunValue availability(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.AvailabilityInputValue inputValue
    );

    @WebResult(name = "AccommodationDetailResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "AccommodationDetail", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.AccommodationDetail")
    @WebMethod(operationName = "AccommodationDetail", action = "http://www.interhome.com/webservice/AccommodationDetail")
    @ResponseWrapper(localName = "AccommodationDetailResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.AccommodationDetailResponse")
    public net.cbtltd.rest.interhome.AccommodationDetailReturnValue accommodationDetail(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.AccommodationDetailInputValue inputValue
    );

    @WebResult(name = "ReadBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "ReadBooking", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.ReadBooking")
    @WebMethod(operationName = "ReadBooking", action = "http://www.interhome.com/webservice/ReadBooking")
    @ResponseWrapper(localName = "ReadBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.ReadBookingResponse")
    public net.cbtltd.rest.interhome.ReadBookingReturnValue readBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.ReadBookingInputValue inputValue
    );

    @WebResult(name = "CancellationConditionsResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "CancellationConditions", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CancellationConditions")
    @WebMethod(operationName = "CancellationConditions", action = "http://www.interhome.com/webservice/CancellationConditions")
    @ResponseWrapper(localName = "CancellationConditionsResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.CancellationConditionsResponse")
    public net.cbtltd.rest.interhome.CancellationConditionReturnValue cancellationConditions(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.CancellationConditionInputValue inputValue
    );

    @WebResult(name = "RatifyBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "RatifyBooking", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.RatifyBooking")
    @WebMethod(operationName = "RatifyBooking", action = "http://www.interhome.com/webservice/RatifyBooking")
    @ResponseWrapper(localName = "RatifyBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.RatifyBookingResponse")
    public net.cbtltd.rest.interhome.RatifyBookingReturnValue ratifyBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.RatifyBookingInputValue inputValue
    );

    @WebResult(name = "ClientBookingResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "ClientBooking", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.ClientBooking")
    @WebMethod(operationName = "ClientBooking", action = "http://www.interhome.com/webservice/ClientBooking")
    @ResponseWrapper(localName = "ClientBookingResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.ClientBookingResponse")
    public net.cbtltd.rest.interhome.ClientBookingReturnValue clientBooking(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.ClientBookingInputValue inputValue
    );

    @WebResult(name = "AdditionalServicesResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "AdditionalServices", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.AdditionalServices")
    @WebMethod(operationName = "AdditionalServices", action = "http://www.interhome.com/webservice/AdditionalServices")
    @ResponseWrapper(localName = "AdditionalServicesResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.AdditionalServicesResponse")
    public net.cbtltd.rest.interhome.AdditionalServicesReturnValue additionalServices(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.AdditionalServicesInputValue inputValue
    );

    @WebResult(name = "PriceListResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "PriceList", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.PriceList")
    @WebMethod(operationName = "PriceList", action = "http://www.interhome.com/webservice/PriceList")
    @ResponseWrapper(localName = "PriceListResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.PriceListResponse")
    public net.cbtltd.rest.interhome.PriceListReturnValue priceList(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.PriceListInputValue inputValue
    );

    @WebResult(name = "TripsResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "Trips", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.Trips")
    @WebMethod(operationName = "Trips", action = "http://www.interhome.com/webservice/Trips")
    @ResponseWrapper(localName = "TripsResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.TripsResponse")
    public net.cbtltd.rest.interhome.TripsReturnValue trips(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.TripsInputValue inputValue
    );

    @WebResult(name = "VoucherDetailResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "VoucherDetail", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.VoucherDetail")
    @WebMethod(operationName = "VoucherDetail", action = "http://www.interhome.com/webservice/VoucherDetail")
    @ResponseWrapper(localName = "VoucherDetailResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.VoucherDetailResponse")
    public net.cbtltd.rest.interhome.VoucherDetailReturnValue voucherDetail(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.VoucherDetailInputValue inputValue
    );

    @WebResult(name = "AffiliateDetailResult", targetNamespace = "http://www.interhome.com/webservice")
    @RequestWrapper(localName = "AffiliateDetail", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.AffiliateDetail")
    @WebMethod(operationName = "AffiliateDetail", action = "http://www.interhome.com/webservice/AffiliateDetail")
    @ResponseWrapper(localName = "AffiliateDetailResponse", targetNamespace = "http://www.interhome.com/webservice", className = "net.cbtltd.rest.interhome.AffiliateDetailResponse")
    public net.cbtltd.rest.interhome.AffiliateDetailReturnValue affiliateDetail(
        @WebParam(name = "inputValue", targetNamespace = "http://www.interhome.com/webservice")
        net.cbtltd.rest.interhome.AffiliateDetailInputValue inputValue
    );
}
