//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 02:42:05 PM IST 
//


package net.cbtltd.rest.atraveo.datamodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.cbtltd.rest.atrevo.datamodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class PricingFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.cbtltd.rest.atrevo.datamodel
     * 
     */
    public PricingFactory() {
    }

    /**
     * Create an instance of {@link PricingFacilities }
     * 
     */
    public PricingFacilities createFacilities() {
        return new PricingFacilities();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility }
     * 
     */
    public PricingFacilities.Facility createFacilitiesFacility() {
        return new PricingFacilities.Facility();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects }
     * 
     */
    public PricingFacilities.Facility.Objects createFacilitiesFacilityObjects() {
        return new PricingFacilities.Facility.Objects();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object }
     * 
     */
    public PricingFacilities.Facility.Objects.Object createFacilitiesFacilityObjectsObject() {
        return new PricingFacilities.Facility.Objects.Object();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.SideCosts }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.SideCosts createFacilitiesFacilityObjectsObjectSideCosts() {
        return new PricingFacilities.Facility.Objects.Object.SideCosts();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.SideCosts.SideCost }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.SideCosts.SideCost createFacilitiesFacilityObjectsObjectSideCostsSideCost() {
        return new PricingFacilities.Facility.Objects.Object.SideCosts.SideCost();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.SideCosts.SideCost.CostInfos }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.SideCosts.SideCost.CostInfos createFacilitiesFacilityObjectsObjectSideCostsSideCostCostInfos() {
        return new PricingFacilities.Facility.Objects.Object.SideCosts.SideCost.CostInfos();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.ObjInfos }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.ObjInfos createFacilitiesFacilityObjectsObjectObjInfos() {
        return new PricingFacilities.Facility.Objects.Object.ObjInfos();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.SpecialOffers }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.SpecialOffers createFacilitiesFacilityObjectsObjectSpecialOffers() {
        return new PricingFacilities.Facility.Objects.Object.SpecialOffers();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.SpecialPeriods }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.SpecialPeriods createFacilitiesFacilityObjectsObjectSpecialPeriods() {
        return new PricingFacilities.Facility.Objects.Object.SpecialPeriods();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.Prices }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.Prices createFacilitiesFacilityObjectsObjectPrices() {
        return new PricingFacilities.Facility.Objects.Object.Prices();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Vacancy }
     * 
     */
    public PricingFacilities.Facility.Vacancy createFacilitiesFacilityVacancy() {
        return new PricingFacilities.Facility.Vacancy();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.Vacancy }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.Vacancy createFacilitiesFacilityObjectsObjectVacancy() {
        return new PricingFacilities.Facility.Objects.Object.Vacancy();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.SideCosts.SideCost.CostInfos.CostInfo }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.SideCosts.SideCost.CostInfos.CostInfo createFacilitiesFacilityObjectsObjectSideCostsSideCostCostInfosCostInfo() {
        return new PricingFacilities.Facility.Objects.Object.SideCosts.SideCost.CostInfos.CostInfo();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.ObjInfos.ObjInfo }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.ObjInfos.ObjInfo createFacilitiesFacilityObjectsObjectObjInfosObjInfo() {
        return new PricingFacilities.Facility.Objects.Object.ObjInfos.ObjInfo();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.SpecialOffers.SpecialOffer }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.SpecialOffers.SpecialOffer createFacilitiesFacilityObjectsObjectSpecialOffersSpecialOffer() {
        return new PricingFacilities.Facility.Objects.Object.SpecialOffers.SpecialOffer();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.SpecialPeriods.SpecialPeriod }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.SpecialPeriods.SpecialPeriod createFacilitiesFacilityObjectsObjectSpecialPeriodsSpecialPeriod() {
        return new PricingFacilities.Facility.Objects.Object.SpecialPeriods.SpecialPeriod();
    }

    /**
     * Create an instance of {@link PricingFacilities.Facility.Objects.Object.Prices.Price }
     * 
     */
    public PricingFacilities.Facility.Objects.Object.Prices.Price createFacilitiesFacilityObjectsObjectPricesPrice() {
        return new PricingFacilities.Facility.Objects.Object.Prices.Price();
    }

}
