package net.cbtltd.rest.leisurelink;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-08-26T16:35:41.391-07:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://LeisureLink.com/RetailWebServices/", name = "RGWServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RGWServiceSoap {

    @WebResult(name = "OTARequestResult", targetNamespace = "http://LeisureLink.com/RetailWebServices/")
    @RequestWrapper(localName = "OTARequest", targetNamespace = "http://LeisureLink.com/RetailWebServices/", className = "net.cbtltd.rest.leisurelink.OTARequest")
    @WebMethod(operationName = "OTARequest", action = "http://LeisureLink.com/RetailWebServices/OTARequest")
    @ResponseWrapper(localName = "OTARequestResponse", targetNamespace = "http://LeisureLink.com/RetailWebServices/", className = "net.cbtltd.rest.leisurelink.OTARequestResponse")
    public java.lang.String otaRequest(
        @WebParam(name = "OTARequest", targetNamespace = "http://LeisureLink.com/RetailWebServices/")
        java.lang.String otaRequest
    );
}
