//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 06:53:05 PM IST 
//


package net.cbtltd.rest.edomizil.xmlexport.datamodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.cbtltd.rest.edomizil.xmlexport.availability package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class AvailabilityFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.cbtltd.rest.edomizil.xmlexport.availability
     * 
     */
    public AvailabilityFactory() {
    }

    /**
     * Create an instance of {@link AvailabilityUnits }
     * 
     */
    public AvailabilityUnits createUnits() {
        return new AvailabilityUnits();
    }

    /**
     * Create an instance of {@link AvailabilityUnits.Unit }
     * 
     */
    public AvailabilityUnits.Unit createUnitsUnit() {
        return new AvailabilityUnits.Unit();
    }

    /**
     * Create an instance of {@link AvailabilityUnits.Unit.AvailabilityYear }
     * 
     */
    public AvailabilityUnits.Unit.AvailabilityYear createUnitsUnitAvailabilityYear() {
        return new AvailabilityUnits.Unit.AvailabilityYear();
    }

    /**
     * Create an instance of {@link AvailabilityUnits.Unit.AvailabilityYear.Availability }
     * 
     */
    public AvailabilityUnits.Unit.AvailabilityYear.Availability createUnitsUnitAvailabilityYearAvailability() {
        return new AvailabilityUnits.Unit.AvailabilityYear.Availability();
    }

}
