//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 09:44:01 AM IST 
//


package net.cbtltd.rest.nextpax;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rangeFromOrRangeToOrAlternativeTypeList"
})
@XmlRootElement(name = "Alternative")
public class Alternative {

    @XmlAttribute(name = "ElementName", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String elementName;
    @XmlAttribute(name = "Ranking")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String ranking;
    @XmlElements({
        @XmlElement(name = "RangeFrom", type = RangeFrom.class),
        @XmlElement(name = "RangeTo", type = RangeTo.class),
        @XmlElement(name = "AlternativeTypeList", type = AlternativeTypeList.class)
    })
    protected List<Object> rangeFromOrRangeToOrAlternativeTypeList;

    /**
     * Gets the value of the elementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementName() {
        return elementName;
    }

    /**
     * Sets the value of the elementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementName(String value) {
        this.elementName = value;
    }

    /**
     * Gets the value of the ranking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRanking() {
        return ranking;
    }

    /**
     * Sets the value of the ranking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRanking(String value) {
        this.ranking = value;
    }

    /**
     * Gets the value of the rangeFromOrRangeToOrAlternativeTypeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rangeFromOrRangeToOrAlternativeTypeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRangeFromOrRangeToOrAlternativeTypeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RangeFrom }
     * {@link RangeTo }
     * {@link AlternativeTypeList }
     * 
     * 
     */
    public List<Object> getRangeFromOrRangeToOrAlternativeTypeList() {
        if (rangeFromOrRangeToOrAlternativeTypeList == null) {
            rangeFromOrRangeToOrAlternativeTypeList = new ArrayList<Object>();
        }
        return this.rangeFromOrRangeToOrAlternativeTypeList;
    }

}
