//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 09:44:01 AM IST 
//


package net.cbtltd.rest.nextpax;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paxDetails",
    "paxAssignment"
})
@XmlRootElement(name = "AssignRequest")
public class AssignRequest {

    @XmlElement(name = "PaxDetails", required = true)
    protected PaxDetails paxDetails;
    @XmlElement(name = "PaxAssignment", required = true)
    protected PaxAssignment paxAssignment;

    /**
     * Gets the value of the paxDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PaxDetails }
     *     
     */
    public PaxDetails getPaxDetails() {
        return paxDetails;
    }

    /**
     * Sets the value of the paxDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaxDetails }
     *     
     */
    public void setPaxDetails(PaxDetails value) {
        this.paxDetails = value;
    }

    /**
     * Gets the value of the paxAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link PaxAssignment }
     *     
     */
    public PaxAssignment getPaxAssignment() {
        return paxAssignment;
    }

    /**
     * Sets the value of the paxAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaxAssignment }
     *     
     */
    public void setPaxAssignment(PaxAssignment value) {
        this.paxAssignment = value;
    }

}
