//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 09:44:01 AM IST 
//


package net.cbtltd.rest.nextpax;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "componentID",
    "sequence",
    "componentType",
    "numberOfAdults",
    "numberOfChildren",
    "numberOfBabies",
    "arrivalDate",
    "departureDateOrDuration"
})
@XmlRootElement(name = "ComponentDetails")
public class ComponentDetails {

    @XmlElement(name = "ComponentID", required = true)
    protected ComponentID componentID;
    @XmlElement(name = "Sequence", required = true)
    protected Sequence sequence;
    @XmlElement(name = "ComponentType", required = true)
    protected String componentType;
    @XmlElement(name = "NumberOfAdults", required = true)
    protected NumberOfAdults numberOfAdults;
    @XmlElement(name = "NumberOfChildren", required = true)
    protected NumberOfChildren numberOfChildren;
    @XmlElement(name = "NumberOfBabies", required = true)
    protected NumberOfBabies numberOfBabies;
    @XmlElement(name = "ArrivalDate", required = true)
    protected String arrivalDate;
    @XmlElements({
        @XmlElement(name = "DepartureDate", required = true, type = DepartureDate.class),
        @XmlElement(name = "Duration", required = true, type = Duration.class)
    })
    protected List<Object> departureDateOrDuration;

    /**
     * Gets the value of the componentID property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentID }
     *     
     */
    public ComponentID getComponentID() {
        return componentID;
    }

    /**
     * Sets the value of the componentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentID }
     *     
     */
    public void setComponentID(ComponentID value) {
        this.componentID = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link Sequence }
     *     
     */
    public Sequence getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sequence }
     *     
     */
    public void setSequence(Sequence value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the componentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentType() {
        return componentType;
    }

    /**
     * Sets the value of the componentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentType(String value) {
        this.componentType = value;
    }

    /**
     * Gets the value of the numberOfAdults property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfAdults }
     *     
     */
    public NumberOfAdults getNumberOfAdults() {
        return numberOfAdults;
    }

    /**
     * Sets the value of the numberOfAdults property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfAdults }
     *     
     */
    public void setNumberOfAdults(NumberOfAdults value) {
        this.numberOfAdults = value;
    }

    /**
     * Gets the value of the numberOfChildren property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfChildren }
     *     
     */
    public NumberOfChildren getNumberOfChildren() {
        return numberOfChildren;
    }

    /**
     * Sets the value of the numberOfChildren property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfChildren }
     *     
     */
    public void setNumberOfChildren(NumberOfChildren value) {
        this.numberOfChildren = value;
    }

    /**
     * Gets the value of the numberOfBabies property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfBabies }
     *     
     */
    public NumberOfBabies getNumberOfBabies() {
        return numberOfBabies;
    }

    /**
     * Sets the value of the numberOfBabies property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfBabies }
     *     
     */
    public void setNumberOfBabies(NumberOfBabies value) {
        this.numberOfBabies = value;
    }

    /**
     * Gets the value of the arrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalDate(String value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the departureDateOrDuration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the departureDateOrDuration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepartureDateOrDuration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DepartureDate }
     * {@link Duration }
     * 
     * 
     */
    public List<Object> getDepartureDateOrDuration() {
        if (departureDateOrDuration == null) {
            departureDateOrDuration = new ArrayList<Object>();
        }
        return this.departureDateOrDuration;
    }

}
