//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 09:44:01 AM IST 
//


package net.cbtltd.rest.nextpax;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "senderEmail",
    "senderTelephone",
    "senderFax",
    "senderOnBehalfOfID",
    "tourOperator",
    "bookID",
    "dossierTravelAgent",
    "destination",
    "clientName",
    "price"
})
@XmlRootElement(name = "ComplaintDetails")
public class ComplaintDetails {

    @XmlElement(name = "SenderEmail", required = true)
    protected String senderEmail;
    @XmlElement(name = "SenderTelephone", required = true)
    protected String senderTelephone;
    @XmlElement(name = "SenderFax")
    protected String senderFax;
    @XmlElement(name = "SenderOnBehalfOfID")
    protected String senderOnBehalfOfID;
    @XmlElement(name = "TourOperator", required = true)
    protected String tourOperator;
    @XmlElement(name = "BookID", required = true)
    protected String bookID;
    @XmlElement(name = "DossierTravelAgent", required = true)
    protected String dossierTravelAgent;
    @XmlElement(name = "Destination", required = true)
    protected Destination destination;
    @XmlElement(name = "ClientName", required = true)
    protected String clientName;
    @XmlElement(name = "Price", required = true)
    protected Price price;

    /**
     * Gets the value of the senderEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderEmail() {
        return senderEmail;
    }

    /**
     * Sets the value of the senderEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderEmail(String value) {
        this.senderEmail = value;
    }

    /**
     * Gets the value of the senderTelephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderTelephone() {
        return senderTelephone;
    }

    /**
     * Sets the value of the senderTelephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderTelephone(String value) {
        this.senderTelephone = value;
    }

    /**
     * Gets the value of the senderFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderFax() {
        return senderFax;
    }

    /**
     * Sets the value of the senderFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderFax(String value) {
        this.senderFax = value;
    }

    /**
     * Gets the value of the senderOnBehalfOfID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderOnBehalfOfID() {
        return senderOnBehalfOfID;
    }

    /**
     * Sets the value of the senderOnBehalfOfID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderOnBehalfOfID(String value) {
        this.senderOnBehalfOfID = value;
    }

    /**
     * Gets the value of the tourOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTourOperator() {
        return tourOperator;
    }

    /**
     * Sets the value of the tourOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTourOperator(String value) {
        this.tourOperator = value;
    }

    /**
     * Gets the value of the bookID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookID() {
        return bookID;
    }

    /**
     * Sets the value of the bookID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookID(String value) {
        this.bookID = value;
    }

    /**
     * Gets the value of the dossierTravelAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDossierTravelAgent() {
        return dossierTravelAgent;
    }

    /**
     * Sets the value of the dossierTravelAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDossierTravelAgent(String value) {
        this.dossierTravelAgent = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link Destination }
     *     
     */
    public Destination getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Destination }
     *     
     */
    public void setDestination(Destination value) {
        this.destination = value;
    }

    /**
     * Gets the value of the clientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * Sets the value of the clientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientName(String value) {
        this.clientName = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link Price }
     *     
     */
    public Price getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link Price }
     *     
     */
    public void setPrice(Price value) {
        this.price = value;
    }

}
