//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 09:44:01 AM IST 
//


package net.cbtltd.rest.nextpax;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentType",
    "documentDelivery",
    "documentAddressType"
})
@XmlRootElement(name = "Document")
public class Document {

    @XmlElement(name = "DocumentType", required = true)
    protected DocumentType documentType;
    @XmlElement(name = "DocumentDelivery", required = true)
    protected DocumentDelivery documentDelivery;
    @XmlElement(name = "DocumentAddressType", required = true)
    protected List<DocumentAddressType> documentAddressType;

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentType }
     *     
     */
    public DocumentType getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentType }
     *     
     */
    public void setDocumentType(DocumentType value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the documentDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentDelivery }
     *     
     */
    public DocumentDelivery getDocumentDelivery() {
        return documentDelivery;
    }

    /**
     * Sets the value of the documentDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentDelivery }
     *     
     */
    public void setDocumentDelivery(DocumentDelivery value) {
        this.documentDelivery = value;
    }

    /**
     * Gets the value of the documentAddressType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentAddressType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentAddressType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentAddressType }
     * 
     * 
     */
    public List<DocumentAddressType> getDocumentAddressType() {
        if (documentAddressType == null) {
            documentAddressType = new ArrayList<DocumentAddressType>();
        }
        return this.documentAddressType;
    }

}
