//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 09:44:01 AM IST 
//


package net.cbtltd.rest.nextpax;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tgroup"
})
@XmlRootElement(name = "Table")
public class Table {

    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tabstyle;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String tocentry;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String shortentry;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String frame;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String colsep;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rowsep;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String orient;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pgwide;
    @XmlElement(required = true)
    protected List<Tgroup> tgroup;

    /**
     * Gets the value of the tabstyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabstyle() {
        return tabstyle;
    }

    /**
     * Sets the value of the tabstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabstyle(String value) {
        this.tabstyle = value;
    }

    /**
     * Gets the value of the tocentry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTocentry() {
        if (tocentry == null) {
            return "1";
        } else {
            return tocentry;
        }
    }

    /**
     * Sets the value of the tocentry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTocentry(String value) {
        this.tocentry = value;
    }

    /**
     * Gets the value of the shortentry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortentry() {
        return shortentry;
    }

    /**
     * Sets the value of the shortentry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortentry(String value) {
        this.shortentry = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrame(String value) {
        this.frame = value;
    }

    /**
     * Gets the value of the colsep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColsep() {
        return colsep;
    }

    /**
     * Sets the value of the colsep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColsep(String value) {
        this.colsep = value;
    }

    /**
     * Gets the value of the rowsep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRowsep() {
        return rowsep;
    }

    /**
     * Sets the value of the rowsep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRowsep(String value) {
        this.rowsep = value;
    }

    /**
     * Gets the value of the orient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrient() {
        return orient;
    }

    /**
     * Sets the value of the orient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrient(String value) {
        this.orient = value;
    }

    /**
     * Gets the value of the pgwide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgwide() {
        return pgwide;
    }

    /**
     * Sets the value of the pgwide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgwide(String value) {
        this.pgwide = value;
    }

    /**
     * Gets the value of the tgroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tgroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTgroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tgroup }
     * 
     * 
     */
    public List<Tgroup> getTgroup() {
        if (tgroup == null) {
            tgroup = new ArrayList<Tgroup>();
        }
        return this.tgroup;
    }

}
