//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.05 at 09:44:01 AM IST 
//


package net.cbtltd.rest.nextpax;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transportRentalID",
    "description",
    "location",
    "category",
    "pickUp",
    "dropOff"
})
@XmlRootElement(name = "TransportRentalComponent")
public class TransportRentalComponent {

    @XmlElement(name = "TransportRentalID", required = true)
    protected String transportRentalID;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Location")
    protected Location location;
    @XmlElement(name = "Category")
    protected String category;
    @XmlElement(name = "PickUp", required = true)
    protected PickUp pickUp;
    @XmlElement(name = "DropOff", required = true)
    protected DropOff dropOff;

    /**
     * Gets the value of the transportRentalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportRentalID() {
        return transportRentalID;
    }

    /**
     * Sets the value of the transportRentalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportRentalID(String value) {
        this.transportRentalID = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the pickUp property.
     * 
     * @return
     *     possible object is
     *     {@link PickUp }
     *     
     */
    public PickUp getPickUp() {
        return pickUp;
    }

    /**
     * Sets the value of the pickUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickUp }
     *     
     */
    public void setPickUp(PickUp value) {
        this.pickUp = value;
    }

    /**
     * Gets the value of the dropOff property.
     * 
     * @return
     *     possible object is
     *     {@link DropOff }
     *     
     */
    public DropOff getDropOff() {
        return dropOff;
    }

    /**
     * Sets the value of the dropOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link DropOff }
     *     
     */
    public void setDropOff(DropOff value) {
        this.dropOff = value;
    }

}
